# CMIP5: Processing Precip Amounts, 2011-2040

This notebook provides for preliminary processing of precipitation amounts primarily to break up the enormous wet days archive. Want to break this into months and save two different DataFrames:

1. Wet Day Counts
2. Precipitation depths

Then we can proceed to distribution fitting.

Go through a month at a time and create the monthly DataFrame for analysis and then output it for distribution fitting in R.

After outputting then analyze the various DataFrames graphically and output some summary statistics to save from doing this in R.

From Wilks & Wilby (1999)
*"Most stochastic weather generators make the assumption that precipitation amounts
on wet days are independent, and follow the same distribution. Allowing different
probability distributions for precipitation amounts depending on that dayâ€™s position in
a wet spell (e.g., the mean rainfall on a wet day following a wet day might be greater
than on a wet day following a dry day) has been considered by Katz (1977), Buishand
(1977; 1978), Chin and Miller (1980) and Wilks (1999a), but allowing this extra
complexity often makes little difference to the result. Similarly, the autocorrelation
between successive nonzero precipitation amounts in daily series is sometimes (statistically) significantly different from zero, but is typically quite small and usually of little
practical importance (Katz, 1977; Buishand, 1977; 1978; Foufoula-Georgiou and
Lettenmaier, 1987). In contrast, accounting for serial correlation of nonzero precipitation
amounts is essential if the precipitation model has an hourly (or smaller) rather than a
daily time step (Katz and Parlange, 1995)."*

In [1]:
from IPython.display import display, HTML
import os
import numpy as np
import pandas as pd
import datetime as dt
import geopandas as gpd
from copy import deepcopy
import re

In [2]:
OUT_DIR = r'\\augustine.space.swri.edu\jdrive\Groundwater\R8937_Stochastic_CC_Recharge\Da' \
          r'ta\JNotes\Processed\CMIP5\CMIP5_2011_WetDays'

Have a DataFrame saved as a pickle file of all of the wet days. Use this as the base for the calculations in this notebook

In [3]:
IN_LOCAP = r'\\augustine.space.swri.edu\jdrive\Groundwater\R8937_Stochastic_CC_Recharge\Da' \
            r'ta\JNotes\Processed\CMIP5\WetDays_LOCA_2011-2040.pickle'
IN_BCCAP = r'\\augustine.space.swri.edu\jdrive\Groundwater\R8937_Stochastic_CC_Recharge\Da' \
            r'ta\JNotes\Processed\CMIP5\WetDays_BCCA_2011-2040.pickle'

In [4]:
LOWetDF = pd.read_pickle( IN_LOCAP )

In [5]:
display( HTML( LOWetDF.head().to_html() ) )

In [6]:
BCWetDF = pd.read_pickle( IN_BCCAP )

In [7]:
display( HTML( BCWetDF.head().to_html() ) )

In [8]:
ExModNum = lambda GId: int( (re.match( r'M(.*[0-9])_(.*[0-9])', GId )).group(1) )
ExGridNum = lambda GId: int( (re.match( r'M(.*[0-9])_(.*[0-9])', GId )).group(2) )

## Monthly Data

Now will split this DataFrame up by month, keeping the grid cell id, and only the other needed columns

In [9]:
LOAllCols = list( LOWetDF.columns )
LOAllCols[:7]

['MGrid_Id', 'Grid_Id', 'Mod_Id', 'Year', 'Month', 'Day', 'Wet_Count']

In [10]:
BCAllCols = list( BCWetDF.columns )
BCAllCols[:7]

['MGrid_Id', 'Grid_Id', 'Mod_Id', 'Year', 'Month', 'Day', 'Wet_Count']

In [11]:
LORootCols = deepcopy( LOAllCols[:7] )
LODayCols = deepcopy( LOAllCols[6:] )

In [12]:
BCRootCols = deepcopy( BCAllCols[:7] )
BCDayCols = deepcopy( BCAllCols[6:] )

In [13]:
LOMaxDays = LOWetDF['Wet_Count'].max()
LOMaxDays

37

In [14]:
BCMaxDays = BCWetDF['Wet_Count'].max()
BCMaxDays

59

In [15]:
StartInd = 3

Go through each month and split out the wet days by month and output these for further distribution fitting in R.

### Jan

Counts

In [16]:
LOJanDF = LOWetDF[LORootCols].loc[LOWetDF['Month'] == 1].copy()

In [17]:
display( HTML( LOJanDF.head().to_html() ) )

In [18]:
BCJanDF = BCWetDF[BCRootCols].loc[BCWetDF['Month'] == 1].copy()

In [19]:
display( HTML( BCJanDF.head().to_html() ) )

In [20]:
LOJanDF['Grid_Id'] = LOJanDF.apply( lambda row: ExGridNum(row['MGrid_Id']), axis=1 )
LOJanDF['Model_Id'] = LOJanDF.apply( lambda row: ExModNum(row['MGrid_Id']), axis=1 )
BCJanDF['Grid_Id'] = BCJanDF.apply( lambda row: ExGridNum(row['MGrid_Id']), axis=1 )
BCJanDF['Model_Id'] = BCJanDF.apply( lambda row: ExModNum(row['MGrid_Id']), axis=1 )

In [21]:
display( HTML( LOJanDF.head().to_html() ) )

In [22]:
display( HTML( BCJanDF.head().to_html() ) )

In [23]:
LOJanPCKF = os.path.normpath( os.path.join( OUT_DIR, "Jan_WetCnt_CMIP5_LOCA_2011-2040.pickle" ) )
LOJanDF.to_pickle( LOJanPCKF )
BCJanPCKF = os.path.normpath( os.path.join( OUT_DIR, "Jan_WetCnt_CMIP5_BCCA_2011-2040.pickle" ) )
BCJanDF.to_pickle( BCJanPCKF )

In [24]:
LOJanDF = LOJanDF.reset_index()
LOJanFeatherF = os.path.normpath( os.path.join( OUT_DIR, "Jan_WetCnt_CMIP5_LOCA_2011-2040.feather" ) )
LOJanDF.to_feather( LOJanFeatherF )
BCJanDF = BCJanDF.reset_index()
BCJanFeatherF = os.path.normpath( os.path.join( OUT_DIR, "Jan_WetCnt_CMIP5_BCCA_2011-2040.feather" ) )
BCJanDF.to_feather( BCJanFeatherF )

Depths

In [25]:
LOJanDF = LOWetDF[LOWetDF['Month'] == 1].copy()
BCJanDF = BCWetDF[BCWetDF['Month'] == 1].copy()

In [26]:
display( HTML( LOJanDF.head().to_html() ) )

In [27]:
LOJanMaxCnt = LOJanDF['Wet_Count'].max()
LOJanMaxCnt

14

In [28]:
BCJanMaxCnt = BCJanDF['Wet_Count'].max()
BCJanMaxCnt

18

In [29]:
LOCurCols = [LORootCols[0], LORootCols[4], LORootCols[5] ]
LOCurCols

['MGrid_Id', 'Month', 'Day']

In [30]:
BCCurCols = [BCRootCols[0], BCRootCols[4], BCRootCols[5] ]
BCCurCols

['MGrid_Id', 'Month', 'Day']

In [31]:
for jJ in range(LOJanMaxCnt):
    LOCurCols.append( LODayCols[jJ] )
# end for

In [32]:
for jJ in range(BCJanMaxCnt):
    BCCurCols.append( BCDayCols[jJ] )
# end for

In [33]:
LOJanDF = LOJanDF[LOCurCols].copy()
BCJanDF = BCJanDF[BCCurCols].copy()

In [34]:
LOJanDF.reset_index(drop=True, inplace=True)
BCJanDF.reset_index(drop=True, inplace=True)

In [35]:
display( HTML( LOJanDF.iloc[:10].to_html() ) )

In [36]:
display( HTML( BCJanDF.iloc[:10].to_html() ) )

In [37]:
LOJanTotDays = LOJanDF['Wet_Count'].sum()
LOJanTotDays

1691522

In [38]:
BCJanTotDays = BCJanDF['Wet_Count'].sum()
BCJanTotDays

1330880

Setup the arrays that will use to store all of the wet day precipitation depths

In [39]:
GridIDs = np.zeros( LOJanTotDays, dtype=np.int32 )
ModelIDs = np.zeros( LOJanTotDays, dtype=np.int32 )
PDDepth = np.zeros( LOJanTotDays, dtype=np.float32 )
MGridIDs = [ "%d" % x for x in GridIDs.tolist() ]

In [40]:
LONumJanWet = len( LOJanDF )
LONumJanWet

936856

In [41]:
iCnt = 0
for iI in range(LONumJanWet):
    cRow = LOJanDF.loc[iI]
    cMGridId = cRow.at["MGrid_Id"]
    cNumWet = int( cRow.at["Wet_Count"] )
    cGridId = ExGridNum( cMGridId )
    cModelId = ExModNum( cMGridId )
    for jJ in range(cNumWet):
        cPDep = float( cRow.at[LOCurCols[StartInd+jJ]] )
        MGridIDs[iCnt] = cMGridId
        GridIDs[iCnt] = cGridId
        ModelIDs[iCnt] = cModelId
        PDDepth[iCnt] = cPDep
        iCnt += 1
    # end of inner for
# end of outer for

In [42]:
GridIDs.min(), GridIDs.max()

(1, 168)

In [43]:
PDDepth.min(), PDDepth.max()

(0.20000094, 179.88637)

In [44]:
DataDict = { "MGrid_Id" : MGridIDs,
             "Grid_Id" : GridIDs,
             "Model_Id" : ModelIDs,
             "Precip_mm" : PDDepth, }
LOJanDayDF = pd.DataFrame( data=DataDict )

In [45]:
display( HTML( LOJanDayDF.describe().to_html() ))

Now want to save the January DataFrame as both a pickle and a feather so that can reuse it with both Python and R.

In [46]:
LOJanPCKF = os.path.normpath( os.path.join( OUT_DIR, "Jan_WetDep_CMIP5_LOCA_2011-2040.pickle" ) )
LOJanDayDF.to_pickle( LOJanPCKF )
LOJanFeatherF = os.path.normpath( os.path.join( OUT_DIR, "Jan_WetDep_CMIP5_LOCA_2011-2040.feather" ) )
LOJanDayDF.to_feather( LOJanFeatherF )

Now BCCA, setup the arrays that will use to store all of the wet day precipitation depths

In [47]:
GridIDs = np.zeros( BCJanTotDays, dtype=np.int32 )
ModelIDs = np.zeros( BCJanTotDays, dtype=np.int32 )
PDDepth = np.zeros( BCJanTotDays, dtype=np.float32 )
MGridIDs = [ "%d" % x for x in GridIDs.tolist() ]

In [48]:
BCNumJanWet = len( BCJanDF )
BCNumJanWet

687543

In [49]:
iCnt = 0
for iI in range(BCNumJanWet):
    cRow = BCJanDF.loc[iI]
    cMGridId = cRow.at["MGrid_Id"]
    cNumWet = int( cRow.at["Wet_Count"] )
    cGridId = ExGridNum( cMGridId )
    cModelId = ExModNum( cMGridId )
    for jJ in range(cNumWet):
        cPDep = float( cRow.at[BCCurCols[StartInd+jJ]] )
        MGridIDs[iCnt] = cMGridId
        GridIDs[iCnt] = cGridId
        ModelIDs[iCnt] = cModelId
        PDDepth[iCnt] = cPDep
        iCnt += 1
    # end of inner for
# end of outer for

In [50]:
GridIDs.min(), GridIDs.max()

(169, 210)

In [51]:
PDDepth.min(), PDDepth.max()

(0.20000172, 135.58203)

In [52]:
DataDict = { "MGrid_Id" : MGridIDs,
             "Grid_Id" : GridIDs,
             "Model_Id" : ModelIDs,
             "Precip_mm" : PDDepth, }
BCJanDayDF = pd.DataFrame( data=DataDict )

In [53]:
display( HTML( BCJanDayDF.describe().to_html() ))

Now want to save the January DataFrame as both a pickle and a feather so that can reuse it with both Python and R.

In [54]:
BCJanPCKF = os.path.normpath( os.path.join( OUT_DIR, "Jan_WetDep_CMIP5_BCCA_2011-2040.pickle" ) )
BCJanDayDF.to_pickle( BCJanPCKF )
BCJanFeatherF = os.path.normpath( os.path.join( OUT_DIR, "Jan_WetDep_CMIP5_BCCA_2011-2040.feather" ) )
BCJanDayDF.to_feather( BCJanFeatherF )

### Feb

Counts

In [55]:
LOFebDF = LOWetDF[LORootCols].loc[LOWetDF['Month'] == 2].copy()

In [56]:
display( HTML( LOFebDF.head().to_html() ) )

In [57]:
BCFebDF = BCWetDF[BCRootCols].loc[BCWetDF['Month'] == 2].copy()

In [58]:
display( HTML( BCFebDF.head().to_html() ) )

In [59]:
LOFebDF['Grid_Id'] = LOFebDF.apply( lambda row: ExGridNum(row['MGrid_Id']), axis=1 )
LOFebDF['Model_Id'] = LOFebDF.apply( lambda row: ExModNum(row['MGrid_Id']), axis=1 )
BCFebDF['Grid_Id'] = BCFebDF.apply( lambda row: ExGridNum(row['MGrid_Id']), axis=1 )
BCFebDF['Model_Id'] = BCFebDF.apply( lambda row: ExModNum(row['MGrid_Id']), axis=1 )

In [60]:
display( HTML( LOFebDF.head().to_html() ) )

In [61]:
display( HTML( BCFebDF.head().to_html() ) )

In [62]:
LOFebPCKF = os.path.normpath( os.path.join( OUT_DIR, "Feb_WetCnt_CMIP5_LOCA_2011-2040.pickle" ) )
LOFebDF.to_pickle( LOFebPCKF )
BCFebPCKF = os.path.normpath( os.path.join( OUT_DIR, "Feb_WetCnt_CMIP5_BCCA_2011-2040.pickle" ) )
BCFebDF.to_pickle( BCFebPCKF )

In [63]:
LOFebDF = LOFebDF.reset_index()
LOFebFeatherF = os.path.normpath( os.path.join( OUT_DIR, "Feb_WetCnt_CMIP5_LOCA_2011-2040.feather" ) )
LOFebDF.to_feather( LOFebFeatherF )
BCFebDF = BCFebDF.reset_index()
BCFebFeatherF = os.path.normpath( os.path.join( OUT_DIR, "Feb_WetCnt_CMIP5_BCCA_2011-2040.feather" ) )
BCFebDF.to_feather( BCFebFeatherF )

Depths

In [64]:
LOFebDF = LOWetDF[LOWetDF['Month'] == 2].copy()
BCFebDF = BCWetDF[BCWetDF['Month'] == 2].copy()

In [65]:
display( HTML( LOFebDF.head().to_html() ) )

In [66]:
LOFebMaxCnt = LOFebDF['Wet_Count'].max()
LOFebMaxCnt

16

In [67]:
BCFebMaxCnt = BCFebDF['Wet_Count'].max()
BCFebMaxCnt

19

In [68]:
LOCurCols = [LORootCols[0], LORootCols[4], LORootCols[5] ]
LOCurCols

['MGrid_Id', 'Month', 'Day']

In [69]:
BCCurCols = [BCRootCols[0], BCRootCols[4], BCRootCols[5] ]
BCCurCols

['MGrid_Id', 'Month', 'Day']

In [70]:
for jJ in range(LOFebMaxCnt):
    LOCurCols.append( LODayCols[jJ] )
# end for

In [71]:
for jJ in range(BCFebMaxCnt):
    BCCurCols.append( BCDayCols[jJ] )
# end for

In [72]:
LOFebDF = LOFebDF[LOCurCols].copy()
BCFebDF = BCFebDF[BCCurCols].copy()

In [73]:
LOFebDF.reset_index(drop=True, inplace=True)
BCFebDF.reset_index(drop=True, inplace=True)

In [74]:
display( HTML( LOFebDF.iloc[:10].to_html() ) )

In [75]:
display( HTML( BCFebDF.iloc[:10].to_html() ) )

In [76]:
LOFebTotDays = LOFebDF['Wet_Count'].sum()
LOFebTotDays

1937834

In [77]:
BCFebTotDays = BCFebDF['Wet_Count'].sum()
BCFebTotDays

1363199

Setup the arrays that will use to store all of the wet day precipitation depths

In [78]:
GridIDs = np.zeros( LOFebTotDays, dtype=np.int32 )
ModelIDs = np.zeros( LOFebTotDays, dtype=np.int32 )
PDDepth = np.zeros( LOFebTotDays, dtype=np.float32 )
MGridIDs = [ "%d" % x for x in GridIDs.tolist() ]

In [79]:
LONumFebWet = len( LOFebDF )
LONumFebWet

989777

In [80]:
iCnt = 0
for iI in range(LONumFebWet):
    cRow = LOFebDF.loc[iI]
    cMGridId = cRow.at["MGrid_Id"]
    cNumWet = int( cRow.at["Wet_Count"] )
    cGridId = ExGridNum( cMGridId )
    cModelId = ExModNum( cMGridId )
    for jJ in range(cNumWet):
        cPDep = float( cRow.at[LOCurCols[StartInd+jJ]] )
        MGridIDs[iCnt] = cMGridId
        GridIDs[iCnt] = cGridId
        ModelIDs[iCnt] = cModelId
        PDDepth[iCnt] = cPDep
        iCnt += 1
    # end of inner for
# end of outer for

In [81]:
GridIDs.min(), GridIDs.max()

(1, 168)

In [82]:
PDDepth.min(), PDDepth.max()

(0.20000397, 196.2004)

In [83]:
DataDict = { "MGrid_Id" : MGridIDs,
             "Grid_Id" : GridIDs,
             "Model_Id" : ModelIDs,
             "Precip_mm" : PDDepth, }
LOFebDayDF = pd.DataFrame( data=DataDict )

In [84]:
display( HTML( LOFebDayDF.describe().to_html() ))

Now want to save the Feb DataFrame as both a pickle and a feather so that can reuse it with both Python and R.

In [85]:
LOFebPCKF = os.path.normpath( os.path.join( OUT_DIR, "Feb_WetDep_CMIP5_LOCA_2011-2040.pickle" ) )
LOFebDayDF.to_pickle( LOFebPCKF )
LOFebFeatherF = os.path.normpath( os.path.join( OUT_DIR, "Feb_WetDep_CMIP5_LOCA_2011-2040.feather" ) )
LOFebDayDF.to_feather( LOFebFeatherF )

Now BCCA, setup the arrays that will use to store all of the wet day precipitation depths

In [86]:
GridIDs = np.zeros( BCFebTotDays, dtype=np.int32 )
ModelIDs = np.zeros( BCFebTotDays, dtype=np.int32 )
PDDepth = np.zeros( BCFebTotDays, dtype=np.float32 )
MGridIDs = [ "%d" % x for x in GridIDs.tolist() ]

In [87]:
BCNumFebWet = len( BCFebDF )
BCNumFebWet

681595

In [88]:
iCnt = 0
for iI in range(BCNumFebWet):
    cRow = BCFebDF.loc[iI]
    cMGridId = cRow.at["MGrid_Id"]
    cNumWet = int( cRow.at["Wet_Count"] )
    cGridId = ExGridNum( cMGridId )
    cModelId = ExModNum( cMGridId )
    for jJ in range(cNumWet):
        cPDep = float( cRow.at[BCCurCols[StartInd+jJ]] )
        MGridIDs[iCnt] = cMGridId
        GridIDs[iCnt] = cGridId
        ModelIDs[iCnt] = cModelId
        PDDepth[iCnt] = cPDep
        iCnt += 1
    # end of inner for
# end of outer for

In [89]:
GridIDs.min(), GridIDs.max()

(169, 210)

In [90]:
PDDepth.min(), PDDepth.max()

(0.20000295, 208.4049)

In [91]:
DataDict = { "MGrid_Id" : MGridIDs,
             "Grid_Id" : GridIDs,
             "Model_Id" : ModelIDs,
             "Precip_mm" : PDDepth, }
BCFebDayDF = pd.DataFrame( data=DataDict )

In [92]:
display( HTML( BCFebDayDF.describe().to_html() ))

Now want to save the Feb DataFrame as both a pickle and a feather so that can reuse it with both Python and R.

In [93]:
BCFebPCKF = os.path.normpath( os.path.join( OUT_DIR, "Feb_WetDep_CMIP5_BCCA_2011-2040.pickle" ) )
BCFebDayDF.to_pickle( BCFebPCKF )
BCFebFeatherF = os.path.normpath( os.path.join( OUT_DIR, "Feb_WetDep_CMIP5_BCCA_2011-2040.feather" ) )
BCFebDayDF.to_feather( BCFebFeatherF )

### Mar

Counts

In [94]:
LOMarDF = LOWetDF[LORootCols].loc[LOWetDF['Month'] == 3].copy()

In [95]:
display( HTML( LOMarDF.head().to_html() ) )

In [96]:
BCMarDF = BCWetDF[BCRootCols].loc[BCWetDF['Month'] == 3].copy()

In [97]:
display( HTML( BCMarDF.head().to_html() ) )

In [98]:
LOMarDF['Grid_Id'] = LOMarDF.apply( lambda row: ExGridNum(row['MGrid_Id']), axis=1 )
LOMarDF['Model_Id'] = LOMarDF.apply( lambda row: ExModNum(row['MGrid_Id']), axis=1 )
BCMarDF['Grid_Id'] = BCMarDF.apply( lambda row: ExGridNum(row['MGrid_Id']), axis=1 )
BCMarDF['Model_Id'] = BCMarDF.apply( lambda row: ExModNum(row['MGrid_Id']), axis=1 )

In [99]:
display( HTML( LOMarDF.head().to_html() ) )

In [100]:
display( HTML( BCMarDF.head().to_html() ) )

In [101]:
LOMarPCKF = os.path.normpath( os.path.join( OUT_DIR, "Mar_WetCnt_CMIP5_LOCA_2011-2040.pickle" ) )
LOMarDF.to_pickle( LOMarPCKF )
BCMarPCKF = os.path.normpath( os.path.join( OUT_DIR, "Mar_WetCnt_CMIP5_BCCA_2011-2040.pickle" ) )
BCMarDF.to_pickle( BCMarPCKF )

In [102]:
LOMarDF = LOMarDF.reset_index()
LOMarFeatherF = os.path.normpath( os.path.join( OUT_DIR, "Mar_WetCnt_CMIP5_LOCA_2011-2040.feather" ) )
LOMarDF.to_feather( LOMarFeatherF )
BCMarDF = BCMarDF.reset_index()
BCMarFeatherF = os.path.normpath( os.path.join( OUT_DIR, "Mar_WetCnt_CMIP5_BCCA_2011-2040.feather" ) )
BCMarDF.to_feather( BCMarFeatherF )

Depths

In [103]:
LOMarDF = LOWetDF[LOWetDF['Month'] == 3].copy()
BCMarDF = BCWetDF[BCWetDF['Month'] == 3].copy()

In [104]:
display( HTML( LOMarDF.head().to_html() ) )

In [105]:
LOMarMaxCnt = LOMarDF['Wet_Count'].max()
LOMarMaxCnt

17

In [106]:
BCMarMaxCnt = BCMarDF['Wet_Count'].max()
BCMarMaxCnt

25

In [107]:
LOCurCols = [LORootCols[0], LORootCols[4], LORootCols[5] ]
LOCurCols

['MGrid_Id', 'Month', 'Day']

In [108]:
BCCurCols = [BCRootCols[0], BCRootCols[4], BCRootCols[5] ]
BCCurCols

['MGrid_Id', 'Month', 'Day']

In [109]:
for jJ in range(LOMarMaxCnt):
    LOCurCols.append( LODayCols[jJ] )
# end for

In [110]:
for jJ in range(BCMarMaxCnt):
    BCCurCols.append( BCDayCols[jJ] )
# end for

In [111]:
LOMarDF = LOMarDF[LOCurCols].copy()
BCMarDF = BCMarDF[BCCurCols].copy()

In [112]:
LOMarDF.reset_index(drop=True, inplace=True)
BCMarDF.reset_index(drop=True, inplace=True)

In [113]:
display( HTML( LOMarDF.iloc[:10].to_html() ) )

In [114]:
display( HTML( BCMarDF.iloc[:10].to_html() ) )

In [115]:
LOMarTotDays = LOMarDF['Wet_Count'].sum()
LOMarTotDays

2051822

In [116]:
BCMarTotDays = BCMarDF['Wet_Count'].sum()
BCMarTotDays

1536892

Setup the arrays that will use to store all of the wet day precipitation depths

In [117]:
GridIDs = np.zeros( LOMarTotDays, dtype=np.int32 )
ModelIDs = np.zeros( LOMarTotDays, dtype=np.int32 )
PDDepth = np.zeros( LOMarTotDays, dtype=np.float32 )
MGridIDs = [ "%d" % x for x in GridIDs.tolist() ]

In [118]:
LONumMarWet = len( LOMarDF )
LONumMarWet

1073267

In [119]:
iCnt = 0
for iI in range(LONumMarWet):
    cRow = LOMarDF.loc[iI]
    cMGridId = cRow.at["MGrid_Id"]
    cNumWet = int( cRow.at["Wet_Count"] )
    cGridId = ExGridNum( cMGridId )
    cModelId = ExModNum( cMGridId )
    for jJ in range(cNumWet):
        cPDep = float( cRow.at[LOCurCols[StartInd+jJ]] )
        MGridIDs[iCnt] = cMGridId
        GridIDs[iCnt] = cGridId
        ModelIDs[iCnt] = cModelId
        PDDepth[iCnt] = cPDep
        iCnt += 1
    # end of inner for
# end of outer for

In [120]:
GridIDs.min(), GridIDs.max()

(1, 168)

In [121]:
PDDepth.min(), PDDepth.max()

(0.20000091, 222.96458)

In [122]:
DataDict = { "MGrid_Id" : MGridIDs,
             "Grid_Id" : GridIDs,
             "Model_Id" : ModelIDs,
             "Precip_mm" : PDDepth, }
LOMarDayDF = pd.DataFrame( data=DataDict )

In [123]:
display( HTML( LOMarDayDF.describe().to_html() ))

Now want to save the Mar DataFrame as both a pickle and a feather so that can reuse it with both Python and R.

In [124]:
LOMarPCKF = os.path.normpath( os.path.join( OUT_DIR, "Mar_WetDep_CMIP5_LOCA_2011-2040.pickle" ) )
LOMarDayDF.to_pickle( LOMarPCKF )
LOMarFeatherF = os.path.normpath( os.path.join( OUT_DIR, "Mar_WetDep_CMIP5_LOCA_2011-2040.feather" ) )
LOMarDayDF.to_feather( LOMarFeatherF )

Now BCCA, setup the arrays that will use to store all of the wet day precipitation depths

In [125]:
GridIDs = np.zeros( BCMarTotDays, dtype=np.int32 )
ModelIDs = np.zeros( BCMarTotDays, dtype=np.int32 )
PDDepth = np.zeros( BCMarTotDays, dtype=np.float32 )
MGridIDs = [ "%d" % x for x in GridIDs.tolist() ]

In [126]:
BCNumMarWet = len( BCMarDF )
BCNumMarWet

771605

In [127]:
iCnt = 0
for iI in range(BCNumMarWet):
    cRow = BCMarDF.loc[iI]
    cMGridId = cRow.at["MGrid_Id"]
    cNumWet = int( cRow.at["Wet_Count"] )
    cGridId = ExGridNum( cMGridId )
    cModelId = ExModNum( cMGridId )
    for jJ in range(cNumWet):
        cPDep = float( cRow.at[BCCurCols[StartInd+jJ]] )
        MGridIDs[iCnt] = cMGridId
        GridIDs[iCnt] = cGridId
        ModelIDs[iCnt] = cModelId
        PDDepth[iCnt] = cPDep
        iCnt += 1
    # end of inner for
# end of outer for

In [128]:
GridIDs.min(), GridIDs.max()

(169, 210)

In [129]:
PDDepth.min(), PDDepth.max()

(0.20000063, 189.59108)

In [130]:
DataDict = { "MGrid_Id" : MGridIDs,
             "Grid_Id" : GridIDs,
             "Model_Id" : ModelIDs,
             "Precip_mm" : PDDepth, }
BCMarDayDF = pd.DataFrame( data=DataDict )

In [131]:
display( HTML( BCMarDayDF.describe().to_html() ))

Now want to save the Mar DataFrame as both a pickle and a feather so that can reuse it with both Python and R.

In [132]:
BCMarPCKF = os.path.normpath( os.path.join( OUT_DIR, "Mar_WetDep_CMIP5_BCCA_2011-2040.pickle" ) )
BCMarDayDF.to_pickle( BCMarPCKF )
BCMarFeatherF = os.path.normpath( os.path.join( OUT_DIR, "Mar_WetDep_CMIP5_BCCA_2011-2040.feather" ) )
BCMarDayDF.to_feather( BCMarFeatherF )

### Apr

Counts

In [133]:
LOAprDF = LOWetDF[LORootCols].loc[LOWetDF['Month'] == 4].copy()

In [134]:
display( HTML( LOAprDF.head().to_html() ) )

In [135]:
BCAprDF = BCWetDF[BCRootCols].loc[BCWetDF['Month'] == 4].copy()

In [136]:
display( HTML( BCAprDF.head().to_html() ) )

In [137]:
LOAprDF['Grid_Id'] = LOAprDF.apply( lambda row: ExGridNum(row['MGrid_Id']), axis=1 )
LOAprDF['Model_Id'] = LOAprDF.apply( lambda row: ExModNum(row['MGrid_Id']), axis=1 )
BCAprDF['Grid_Id'] = BCAprDF.apply( lambda row: ExGridNum(row['MGrid_Id']), axis=1 )
BCAprDF['Model_Id'] = BCAprDF.apply( lambda row: ExModNum(row['MGrid_Id']), axis=1 )

In [138]:
display( HTML( LOAprDF.head().to_html() ) )

In [139]:
display( HTML( BCAprDF.head().to_html() ) )

In [140]:
LOAprPCKF = os.path.normpath( os.path.join( OUT_DIR, "Apr_WetCnt_CMIP5_LOCA_2011-2040.pickle" ) )
LOAprDF.to_pickle( LOAprPCKF )
BCAprPCKF = os.path.normpath( os.path.join( OUT_DIR, "Apr_WetCnt_CMIP5_BCCA_2011-2040.pickle" ) )
BCAprDF.to_pickle( BCAprPCKF )

In [141]:
LOAprDF = LOAprDF.reset_index()
LOAprFeatherF = os.path.normpath( os.path.join( OUT_DIR, "Apr_WetCnt_CMIP5_LOCA_2011-2040.feather" ) )
LOAprDF.to_feather( LOAprFeatherF )
BCAprDF = BCAprDF.reset_index()
BCAprFeatherF = os.path.normpath( os.path.join( OUT_DIR, "Apr_WetCnt_CMIP5_BCCA_2011-2040.feather" ) )
BCAprDF.to_feather( BCAprFeatherF )

Depths

In [142]:
LOAprDF = LOWetDF[LOWetDF['Month'] == 4].copy()
BCAprDF = BCWetDF[BCWetDF['Month'] == 4].copy()

In [143]:
display( HTML( LOAprDF.head().to_html() ) )

In [144]:
LOAprMaxCnt = LOAprDF['Wet_Count'].max()
LOAprMaxCnt

27

In [145]:
BCAprMaxCnt = BCAprDF['Wet_Count'].max()
BCAprMaxCnt

44

In [146]:
LOCurCols = [LORootCols[0], LORootCols[4], LORootCols[5] ]
LOCurCols

['MGrid_Id', 'Month', 'Day']

In [147]:
BCCurCols = [BCRootCols[0], BCRootCols[4], BCRootCols[5] ]
BCCurCols

['MGrid_Id', 'Month', 'Day']

In [148]:
for jJ in range(LOAprMaxCnt):
    LOCurCols.append( LODayCols[jJ] )
# end for

In [149]:
for jJ in range(BCAprMaxCnt):
    BCCurCols.append( BCDayCols[jJ] )
# end for

In [150]:
LOAprDF = LOAprDF[LOCurCols].copy()
BCAprDF = BCAprDF[BCCurCols].copy()

In [151]:
LOAprDF.reset_index(drop=True, inplace=True)
BCAprDF.reset_index(drop=True, inplace=True)

In [152]:
display( HTML( LOAprDF.iloc[:10].to_html() ) )

In [153]:
display( HTML( BCAprDF.iloc[:10].to_html() ) )

In [154]:
LOAprTotDays = LOAprDF['Wet_Count'].sum()
LOAprTotDays

2757923

In [155]:
BCAprTotDays = BCAprDF['Wet_Count'].sum()
BCAprTotDays

1959651

Setup the arrays that will use to store all of the wet day precipitation depths

In [156]:
GridIDs = np.zeros( LOAprTotDays, dtype=np.int32 )
ModelIDs = np.zeros( LOAprTotDays, dtype=np.int32 )
PDDepth = np.zeros( LOAprTotDays, dtype=np.float32 )
MGridIDs = [ "%d" % x for x in GridIDs.tolist() ]

In [157]:
LONumAprWet = len( LOAprDF )
LONumAprWet

1223573

In [158]:
iCnt = 0
for iI in range(LONumAprWet):
    cRow = LOAprDF.loc[iI]
    cMGridId = cRow.at["MGrid_Id"]
    cNumWet = int( cRow.at["Wet_Count"] )
    cGridId = ExGridNum( cMGridId )
    cModelId = ExModNum( cMGridId )
    for jJ in range(cNumWet):
        cPDep = float( cRow.at[LOCurCols[StartInd+jJ]] )
        MGridIDs[iCnt] = cMGridId
        GridIDs[iCnt] = cGridId
        ModelIDs[iCnt] = cModelId
        PDDepth[iCnt] = cPDep
        iCnt += 1
    # end of inner for
# end of outer for

In [159]:
GridIDs.min(), GridIDs.max()

(1, 168)

In [160]:
PDDepth.min(), PDDepth.max()

(0.20000081, 288.40182)

In [161]:
DataDict = { "MGrid_Id" : MGridIDs,
             "Grid_Id" : GridIDs,
             "Model_Id" : ModelIDs,
             "Precip_mm" : PDDepth, }
LOAprDayDF = pd.DataFrame( data=DataDict )

In [162]:
display( HTML( LOAprDayDF.describe().to_html() ))

Now want to save the Apr DataFrame as both a pickle and a feather so that can reuse it with both Python and R.

In [163]:
LOAprPCKF = os.path.normpath( os.path.join( OUT_DIR, "Apr_WetDep_CMIP5_LOCA_2011-2040.pickle" ) )
LOAprDayDF.to_pickle( LOAprPCKF )
LOAprFeatherF = os.path.normpath( os.path.join( OUT_DIR, "Apr_WetDep_CMIP5_LOCA_2011-2040.feather" ) )
LOAprDayDF.to_feather( LOAprFeatherF )

Now BCCA, setup the arrays that will use to store all of the wet day precipitation depths

In [164]:
GridIDs = np.zeros( BCAprTotDays, dtype=np.int32 )
ModelIDs = np.zeros( BCAprTotDays, dtype=np.int32 )
PDDepth = np.zeros( BCAprTotDays, dtype=np.float32 )
MGridIDs = [ "%d" % x for x in GridIDs.tolist() ]

In [165]:
BCNumAprWet = len( BCAprDF )
BCNumAprWet

821237

In [166]:
iCnt = 0
for iI in range(BCNumAprWet):
    cRow = BCAprDF.loc[iI]
    cMGridId = cRow.at["MGrid_Id"]
    cNumWet = int( cRow.at["Wet_Count"] )
    cGridId = ExGridNum( cMGridId )
    cModelId = ExModNum( cMGridId )
    for jJ in range(cNumWet):
        cPDep = float( cRow.at[BCCurCols[StartInd+jJ]] )
        MGridIDs[iCnt] = cMGridId
        GridIDs[iCnt] = cGridId
        ModelIDs[iCnt] = cModelId
        PDDepth[iCnt] = cPDep
        iCnt += 1
    # end of inner for
# end of outer for

In [167]:
GridIDs.min(), GridIDs.max()

(169, 210)

In [168]:
PDDepth.min(), PDDepth.max()

(0.20000266, 358.19058)

In [169]:
DataDict = { "MGrid_Id" : MGridIDs,
             "Grid_Id" : GridIDs,
             "Model_Id" : ModelIDs,
             "Precip_mm" : PDDepth, }
BCAprDayDF = pd.DataFrame( data=DataDict )

In [170]:
display( HTML( BCAprDayDF.describe().to_html() ))

Now want to save the Apr DataFrame as both a pickle and a feather so that can reuse it with both Python and R.

In [171]:
BCAprPCKF = os.path.normpath( os.path.join( OUT_DIR, "Apr_WetDep_CMIP5_BCCA_2011-2040.pickle" ) )
BCAprDayDF.to_pickle( BCAprPCKF )
BCAprFeatherF = os.path.normpath( os.path.join( OUT_DIR, "Apr_WetDep_CMIP5_BCCA_2011-2040.feather" ) )
BCAprDayDF.to_feather( BCAprFeatherF )

### May

Counts

In [172]:
LOMayDF = LOWetDF[LORootCols].loc[LOWetDF['Month'] == 5].copy()

In [173]:
display( HTML( LOMayDF.head().to_html() ) )

In [174]:
BCMayDF = BCWetDF[BCRootCols].loc[BCWetDF['Month'] == 5].copy()

In [175]:
display( HTML( BCMayDF.head().to_html() ) )

In [176]:
LOMayDF['Grid_Id'] = LOMayDF.apply( lambda row: ExGridNum(row['MGrid_Id']), axis=1 )
LOMayDF['Model_Id'] = LOMayDF.apply( lambda row: ExModNum(row['MGrid_Id']), axis=1 )
BCMayDF['Grid_Id'] = BCMayDF.apply( lambda row: ExGridNum(row['MGrid_Id']), axis=1 )
BCMayDF['Model_Id'] = BCMayDF.apply( lambda row: ExModNum(row['MGrid_Id']), axis=1 )

In [177]:
display( HTML( LOMayDF.head().to_html() ) )

In [178]:
display( HTML( BCMayDF.head().to_html() ) )

In [179]:
LOMayPCKF = os.path.normpath( os.path.join( OUT_DIR, "May_WetCnt_CMIP5_LOCA_2011-2040.pickle" ) )
LOMayDF.to_pickle( LOMayPCKF )
BCMayPCKF = os.path.normpath( os.path.join( OUT_DIR, "May_WetCnt_CMIP5_BCCA_2011-2040.pickle" ) )
BCMayDF.to_pickle( BCMayPCKF )

In [180]:
LOMayDF = LOMayDF.reset_index()
LOMayFeatherF = os.path.normpath( os.path.join( OUT_DIR, "May_WetCnt_CMIP5_LOCA_2011-2040.feather" ) )
LOMayDF.to_feather( LOMayFeatherF )
BCMayDF = BCMayDF.reset_index()
BCMayFeatherF = os.path.normpath( os.path.join( OUT_DIR, "May_WetCnt_CMIP5_BCCA_2011-2040.feather" ) )
BCMayDF.to_feather( BCMayFeatherF )

Depths

In [181]:
LOMayDF = LOWetDF[LOWetDF['Month'] == 5].copy()
BCMayDF = BCWetDF[BCWetDF['Month'] == 5].copy()

In [182]:
display( HTML( LOMayDF.head().to_html() ) )

In [183]:
LOMayMaxCnt = LOMayDF['Wet_Count'].max()
LOMayMaxCnt

33

In [184]:
BCMayMaxCnt = BCMayDF['Wet_Count'].max()
BCMayMaxCnt

47

In [185]:
LOCurCols = [LORootCols[0], LORootCols[4], LORootCols[5] ]
LOCurCols

['MGrid_Id', 'Month', 'Day']

In [186]:
BCCurCols = [BCRootCols[0], BCRootCols[4], BCRootCols[5] ]
BCCurCols

['MGrid_Id', 'Month', 'Day']

In [187]:
for jJ in range(LOMayMaxCnt):
    LOCurCols.append( LODayCols[jJ] )
# end for

In [188]:
for jJ in range(BCMayMaxCnt):
    BCCurCols.append( BCDayCols[jJ] )
# end for

In [189]:
LOMayDF = LOMayDF[LOCurCols].copy()
BCMayDF = BCMayDF[BCCurCols].copy()

In [190]:
LOMayDF.reset_index(drop=True, inplace=True)
BCMayDF.reset_index(drop=True, inplace=True)

In [191]:
display( HTML( LOMayDF.iloc[:10].to_html() ) )

In [192]:
display( HTML( BCMayDF.iloc[:10].to_html() ) )

In [193]:
LOMayTotDays = LOMayDF['Wet_Count'].sum()
LOMayTotDays

3820683

In [194]:
BCMayTotDays = BCMayDF['Wet_Count'].sum()
BCMayTotDays

2731478

Setup the arrays that will use to store all of the wet day precipitation depths

In [195]:
GridIDs = np.zeros( LOMayTotDays, dtype=np.int32 )
ModelIDs = np.zeros( LOMayTotDays, dtype=np.int32 )
PDDepth = np.zeros( LOMayTotDays, dtype=np.float32 )
MGridIDs = [ "%d" % x for x in GridIDs.tolist() ]

In [196]:
LONumMayWet = len( LOMayDF )
LONumMayWet

1434272

In [197]:
iCnt = 0
for iI in range(LONumMayWet):
    cRow = LOMayDF.loc[iI]
    cMGridId = cRow.at["MGrid_Id"]
    cNumWet = int( cRow.at["Wet_Count"] )
    cGridId = ExGridNum( cMGridId )
    cModelId = ExModNum( cMGridId )
    for jJ in range(cNumWet):
        cPDep = float( cRow.at[LOCurCols[StartInd+jJ]] )
        MGridIDs[iCnt] = cMGridId
        GridIDs[iCnt] = cGridId
        ModelIDs[iCnt] = cModelId
        PDDepth[iCnt] = cPDep
        iCnt += 1
    # end of inner for
# end of outer for

In [198]:
GridIDs.min(), GridIDs.max()

(1, 168)

In [199]:
PDDepth.min(), PDDepth.max()

(0.20000151, 487.73303)

In [200]:
DataDict = { "MGrid_Id" : MGridIDs,
             "Grid_Id" : GridIDs,
             "Model_Id" : ModelIDs,
             "Precip_mm" : PDDepth, }
LOMayDayDF = pd.DataFrame( data=DataDict )

In [201]:
display( HTML( LOMayDayDF.describe().to_html() ))

Now want to save the May DataFrame as both a pickle and a feather so that can reuse it with both Python and R.

In [202]:
LOMayPCKF = os.path.normpath( os.path.join( OUT_DIR, "May_WetDep_CMIP5_LOCA_2011-2040.pickle" ) )
LOMayDayDF.to_pickle( LOMayPCKF )
LOMayFeatherF = os.path.normpath( os.path.join( OUT_DIR, "May_WetDep_CMIP5_LOCA_2011-2040.feather" ) )
LOMayDayDF.to_feather( LOMayFeatherF )

Now BCCA, setup the arrays that will use to store all of the wet day precipitation depths

In [203]:
GridIDs = np.zeros( BCMayTotDays, dtype=np.int32 )
ModelIDs = np.zeros( BCMayTotDays, dtype=np.int32 )
PDDepth = np.zeros( BCMayTotDays, dtype=np.float32 )
MGridIDs = [ "%d" % x for x in GridIDs.tolist() ]

In [204]:
BCNumMayWet = len( BCMayDF )
BCNumMayWet

871799

In [205]:
iCnt = 0
for iI in range(BCNumMayWet):
    cRow = BCMayDF.loc[iI]
    cMGridId = cRow.at["MGrid_Id"]
    cNumWet = int( cRow.at["Wet_Count"] )
    cGridId = ExGridNum( cMGridId )
    cModelId = ExModNum( cMGridId )
    for jJ in range(cNumWet):
        cPDep = float( cRow.at[BCCurCols[StartInd+jJ]] )
        MGridIDs[iCnt] = cMGridId
        GridIDs[iCnt] = cGridId
        ModelIDs[iCnt] = cModelId
        PDDepth[iCnt] = cPDep
        iCnt += 1
    # end of inner for
# end of outer for

In [206]:
GridIDs.min(), GridIDs.max()

(169, 210)

In [207]:
PDDepth.min(), PDDepth.max()

(0.20000012, 649.7718)

In [208]:
DataDict = { "MGrid_Id" : MGridIDs,
             "Grid_Id" : GridIDs,
             "Model_Id" : ModelIDs,
             "Precip_mm" : PDDepth, }
BCMayDayDF = pd.DataFrame( data=DataDict )

In [209]:
display( HTML( BCMayDayDF.describe().to_html() ))

Now want to save the May DataFrame as both a pickle and a feather so that can reuse it with both Python and R.

In [210]:
BCMayPCKF = os.path.normpath( os.path.join( OUT_DIR, "May_WetDep_CMIP5_BCCA_2011-2040.pickle" ) )
BCMayDayDF.to_pickle( BCMayPCKF )
BCMayFeatherF = os.path.normpath( os.path.join( OUT_DIR, "May_WetDep_CMIP5_BCCA_2011-2040.feather" ) )
BCMayDayDF.to_feather( BCMayFeatherF )

### Jun

Counts

In [211]:
LOJunDF = LOWetDF[LORootCols].loc[LOWetDF['Month'] == 6].copy()

In [212]:
display( HTML( LOJunDF.head().to_html() ) )

In [213]:
BCJunDF = BCWetDF[BCRootCols].loc[BCWetDF['Month'] == 6].copy()

In [214]:
display( HTML( BCJunDF.head().to_html() ) )

In [215]:
LOJunDF['Grid_Id'] = LOJunDF.apply( lambda row: ExGridNum(row['MGrid_Id']), axis=1 )
LOJunDF['Model_Id'] = LOJunDF.apply( lambda row: ExModNum(row['MGrid_Id']), axis=1 )
BCJunDF['Grid_Id'] = BCJunDF.apply( lambda row: ExGridNum(row['MGrid_Id']), axis=1 )
BCJunDF['Model_Id'] = BCJunDF.apply( lambda row: ExModNum(row['MGrid_Id']), axis=1 )

In [216]:
display( HTML( LOJunDF.head().to_html() ) )

In [217]:
display( HTML( BCJunDF.head().to_html() ) )

In [218]:
LOJunPCKF = os.path.normpath( os.path.join( OUT_DIR, "Jun_WetCnt_CMIP5_LOCA_2011-2040.pickle" ) )
LOJunDF.to_pickle( LOJunPCKF )
BCJunPCKF = os.path.normpath( os.path.join( OUT_DIR, "Jun_WetCnt_CMIP5_BCCA_2011-2040.pickle" ) )
BCJunDF.to_pickle( BCJunPCKF )

In [219]:
LOJunDF = LOJunDF.reset_index()
LOJunFeatherF = os.path.normpath( os.path.join( OUT_DIR, "Jun_WetCnt_CMIP5_LOCA_2011-2040.feather" ) )
LOJunDF.to_feather( LOJunFeatherF )
BCJunDF = BCJunDF.reset_index()
BCJunFeatherF = os.path.normpath( os.path.join( OUT_DIR, "Jun_WetCnt_CMIP5_BCCA_2011-2040.feather" ) )
BCJunDF.to_feather( BCJunFeatherF )

Depths

In [220]:
LOJunDF = LOWetDF[LOWetDF['Month'] == 6].copy()
BCJunDF = BCWetDF[BCWetDF['Month'] == 6].copy()

In [221]:
display( HTML( LOJunDF.head().to_html() ) )

In [222]:
LOJunMaxCnt = LOJunDF['Wet_Count'].max()
LOJunMaxCnt

36

In [223]:
BCJunMaxCnt = BCJunDF['Wet_Count'].max()
BCJunMaxCnt

54

In [224]:
LOCurCols = [LORootCols[0], LORootCols[4], LORootCols[5] ]
LOCurCols

['MGrid_Id', 'Month', 'Day']

In [225]:
BCCurCols = [BCRootCols[0], BCRootCols[4], BCRootCols[5] ]
BCCurCols

['MGrid_Id', 'Month', 'Day']

In [226]:
for jJ in range(LOJunMaxCnt):
    LOCurCols.append( LODayCols[jJ] )
# end for

In [227]:
for jJ in range(BCJunMaxCnt):
    BCCurCols.append( BCDayCols[jJ] )
# end for

In [228]:
LOJunDF = LOJunDF[LOCurCols].copy()
BCJunDF = BCJunDF[BCCurCols].copy()

In [229]:
LOJunDF.reset_index(drop=True, inplace=True)
BCJunDF.reset_index(drop=True, inplace=True)

In [230]:
display( HTML( LOJunDF.iloc[:10].to_html() ) )

In [231]:
display( HTML( BCJunDF.iloc[:10].to_html() ) )

In [232]:
LOJunTotDays = LOJunDF['Wet_Count'].sum()
LOJunTotDays

3547499

In [233]:
BCJunTotDays = BCJunDF['Wet_Count'].sum()
BCJunTotDays

2325675

Setup the arrays that will use to store all of the wet day precipitation depths

In [234]:
GridIDs = np.zeros( LOJunTotDays, dtype=np.int32 )
ModelIDs = np.zeros( LOJunTotDays, dtype=np.int32 )
PDDepth = np.zeros( LOJunTotDays, dtype=np.float32 )
MGridIDs = [ "%d" % x for x in GridIDs.tolist() ]

In [235]:
LONumJunWet = len( LOJunDF )
LONumJunWet

1201307

In [236]:
iCnt = 0
for iI in range(LONumJunWet):
    cRow = LOJunDF.loc[iI]
    cMGridId = cRow.at["MGrid_Id"]
    cNumWet = int( cRow.at["Wet_Count"] )
    cGridId = ExGridNum( cMGridId )
    cModelId = ExModNum( cMGridId )
    for jJ in range(cNumWet):
        cPDep = float( cRow.at[LOCurCols[StartInd+jJ]] )
        MGridIDs[iCnt] = cMGridId
        GridIDs[iCnt] = cGridId
        ModelIDs[iCnt] = cModelId
        PDDepth[iCnt] = cPDep
        iCnt += 1
    # end of inner for
# end of outer for

In [237]:
GridIDs.min(), GridIDs.max()

(1, 168)

In [238]:
PDDepth.min(), PDDepth.max()

(0.20000094, 582.99133)

In [239]:
DataDict = { "MGrid_Id" : MGridIDs,
             "Grid_Id" : GridIDs,
             "Model_Id" : ModelIDs,
             "Precip_mm" : PDDepth, }
LOJunDayDF = pd.DataFrame( data=DataDict )

In [240]:
display( HTML( LOJunDayDF.describe().to_html() ))

Now want to save the Jun DataFrame as both a pickle and a feather so that can reuse it with both Python and R.

In [241]:
LOJunPCKF = os.path.normpath( os.path.join( OUT_DIR, "Jun_WetDep_CMIP5_LOCA_2011-2040.pickle" ) )
LOJunDayDF.to_pickle( LOJunPCKF )
LOJunFeatherF = os.path.normpath( os.path.join( OUT_DIR, "Jun_WetDep_CMIP5_LOCA_2011-2040.feather" ) )
LOJunDayDF.to_feather( LOJunFeatherF )

Now BCCA, setup the arrays that will use to store all of the wet day precipitation depths

In [242]:
GridIDs = np.zeros( BCJunTotDays, dtype=np.int32 )
ModelIDs = np.zeros( BCJunTotDays, dtype=np.int32 )
PDDepth = np.zeros( BCJunTotDays, dtype=np.float32 )
MGridIDs = [ "%d" % x for x in GridIDs.tolist() ]

In [243]:
BCNumJunWet = len( BCJunDF )
BCNumJunWet

810135

In [244]:
iCnt = 0
for iI in range(BCNumJunWet):
    cRow = BCJunDF.loc[iI]
    cMGridId = cRow.at["MGrid_Id"]
    cNumWet = int( cRow.at["Wet_Count"] )
    cGridId = ExGridNum( cMGridId )
    cModelId = ExModNum( cMGridId )
    for jJ in range(cNumWet):
        cPDep = float( cRow.at[BCCurCols[StartInd+jJ]] )
        MGridIDs[iCnt] = cMGridId
        GridIDs[iCnt] = cGridId
        ModelIDs[iCnt] = cModelId
        PDDepth[iCnt] = cPDep
        iCnt += 1
    # end of inner for
# end of outer for

In [245]:
GridIDs.min(), GridIDs.max()

(169, 210)

In [246]:
PDDepth.min(), PDDepth.max()

(0.20000164, 514.7031)

In [247]:
DataDict = { "MGrid_Id" : MGridIDs,
             "Grid_Id" : GridIDs,
             "Model_Id" : ModelIDs,
             "Precip_mm" : PDDepth, }
BCJunDayDF = pd.DataFrame( data=DataDict )

In [248]:
display( HTML( BCJunDayDF.describe().to_html() ))

Now want to save the Jun DataFrame as both a pickle and a feather so that can reuse it with both Python and R.

In [249]:
BCJunPCKF = os.path.normpath( os.path.join( OUT_DIR, "Jun_WetDep_CMIP5_BCCA_2011-2040.pickle" ) )
BCJunDayDF.to_pickle( BCJunPCKF )
BCJunFeatherF = os.path.normpath( os.path.join( OUT_DIR, "Jun_WetDep_CMIP5_BCCA_2011-2040.feather" ) )
BCJunDayDF.to_feather( BCJunFeatherF )

### Jul

Counts

In [250]:
LOJulDF = LOWetDF[LORootCols].loc[LOWetDF['Month'] == 7].copy()

In [251]:
display( HTML( LOJulDF.head().to_html() ) )

In [252]:
BCJulDF = BCWetDF[BCRootCols].loc[BCWetDF['Month'] == 7].copy()

In [253]:
display( HTML( BCJulDF.head().to_html() ) )

In [254]:
LOJulDF['Grid_Id'] = LOJulDF.apply( lambda row: ExGridNum(row['MGrid_Id']), axis=1 )
LOJulDF['Model_Id'] = LOJulDF.apply( lambda row: ExModNum(row['MGrid_Id']), axis=1 )
BCJulDF['Grid_Id'] = BCJulDF.apply( lambda row: ExGridNum(row['MGrid_Id']), axis=1 )
BCJulDF['Model_Id'] = BCJulDF.apply( lambda row: ExModNum(row['MGrid_Id']), axis=1 )

In [255]:
display( HTML( LOJulDF.head().to_html() ) )

In [256]:
display( HTML( BCJulDF.head().to_html() ) )

In [257]:
LOJulPCKF = os.path.normpath( os.path.join( OUT_DIR, "Jul_WetCnt_CMIP5_LOCA_2011-2040.pickle" ) )
LOJulDF.to_pickle( LOJulPCKF )
BCJulPCKF = os.path.normpath( os.path.join( OUT_DIR, "Jul_WetCnt_CMIP5_BCCA_2011-2040.pickle" ) )
BCJulDF.to_pickle( BCJulPCKF )

In [258]:
LOJulDF = LOJulDF.reset_index()
LOJulFeatherF = os.path.normpath( os.path.join( OUT_DIR, "Jul_WetCnt_CMIP5_LOCA_2011-2040.feather" ) )
LOJulDF.to_feather( LOJulFeatherF )
BCJulDF = BCJulDF.reset_index()
BCJulFeatherF = os.path.normpath( os.path.join( OUT_DIR, "Jul_WetCnt_CMIP5_BCCA_2011-2040.feather" ) )
BCJulDF.to_feather( BCJulFeatherF )

Depths

In [259]:
LOJulDF = LOWetDF[LOWetDF['Month'] == 7].copy()
BCJulDF = BCWetDF[BCWetDF['Month'] == 7].copy()

In [260]:
display( HTML( LOJulDF.head().to_html() ) )

In [261]:
LOJulMaxCnt = LOJulDF['Wet_Count'].max()
LOJulMaxCnt

30

In [262]:
BCJulMaxCnt = BCJulDF['Wet_Count'].max()
BCJulMaxCnt

59

In [263]:
LOCurCols = [LORootCols[0], LORootCols[4], LORootCols[5] ]
LOCurCols

['MGrid_Id', 'Month', 'Day']

In [264]:
BCCurCols = [BCRootCols[0], BCRootCols[4], BCRootCols[5] ]
BCCurCols

['MGrid_Id', 'Month', 'Day']

In [265]:
for jJ in range(LOJulMaxCnt):
    LOCurCols.append( LODayCols[jJ] )
# end for

In [266]:
for jJ in range(BCJulMaxCnt):
    BCCurCols.append( BCDayCols[jJ] )
# end for

In [267]:
LOJulDF = LOJulDF[LOCurCols].copy()
BCJulDF = BCJulDF[BCCurCols].copy()

In [268]:
LOJulDF.reset_index(drop=True, inplace=True)
BCJulDF.reset_index(drop=True, inplace=True)

In [269]:
display( HTML( LOJulDF.iloc[:10].to_html() ) )

In [270]:
display( HTML( BCJulDF.iloc[:10].to_html() ) )

In [271]:
LOJulTotDays = LOJulDF['Wet_Count'].sum()
LOJulTotDays

2633265

In [272]:
BCJulTotDays = BCJulDF['Wet_Count'].sum()
BCJulTotDays

2236930

Setup the arrays that will use to store all of the wet day precipitation depths

In [273]:
GridIDs = np.zeros( LOJulTotDays, dtype=np.int32 )
ModelIDs = np.zeros( LOJulTotDays, dtype=np.int32 )
PDDepth = np.zeros( LOJulTotDays, dtype=np.float32 )
MGridIDs = [ "%d" % x for x in GridIDs.tolist() ]

In [274]:
LONumJulWet = len( LOJulDF )
LONumJulWet

1000367

In [275]:
iCnt = 0
for iI in range(LONumJulWet):
    cRow = LOJulDF.loc[iI]
    cMGridId = cRow.at["MGrid_Id"]
    cNumWet = int( cRow.at["Wet_Count"] )
    cGridId = ExGridNum( cMGridId )
    cModelId = ExModNum( cMGridId )
    for jJ in range(cNumWet):
        cPDep = float( cRow.at[LOCurCols[StartInd+jJ]] )
        MGridIDs[iCnt] = cMGridId
        GridIDs[iCnt] = cGridId
        ModelIDs[iCnt] = cModelId
        PDDepth[iCnt] = cPDep
        iCnt += 1
    # end of inner for
# end of outer for

In [276]:
GridIDs.min(), GridIDs.max()

(1, 168)

In [277]:
PDDepth.min(), PDDepth.max()

(0.20000075, 620.76666)

In [278]:
DataDict = { "MGrid_Id" : MGridIDs,
             "Grid_Id" : GridIDs,
             "Model_Id" : ModelIDs,
             "Precip_mm" : PDDepth, }
LOJulDayDF = pd.DataFrame( data=DataDict )

In [279]:
display( HTML( LOJulDayDF.describe().to_html() ))

Now want to save the Jul DataFrame as both a pickle and a feather so that can reuse it with both Python and R.

In [280]:
LOJulPCKF = os.path.normpath( os.path.join( OUT_DIR, "Jul_WetDep_CMIP5_LOCA_2011-2040.pickle" ) )
LOJulDayDF.to_pickle( LOJulPCKF )
LOJulFeatherF = os.path.normpath( os.path.join( OUT_DIR, "Jul_WetDep_CMIP5_LOCA_2011-2040.feather" ) )
LOJulDayDF.to_feather( LOJulFeatherF )

Now BCCA, setup the arrays that will use to store all of the wet day precipitation depths

In [281]:
GridIDs = np.zeros( BCJulTotDays, dtype=np.int32 )
ModelIDs = np.zeros( BCJulTotDays, dtype=np.int32 )
PDDepth = np.zeros( BCJulTotDays, dtype=np.float32 )
MGridIDs = [ "%d" % x for x in GridIDs.tolist() ]

In [282]:
BCNumJulWet = len( BCJulDF )
BCNumJulWet

852893

In [283]:
iCnt = 0
for iI in range(BCNumJulWet):
    cRow = BCJulDF.loc[iI]
    cMGridId = cRow.at["MGrid_Id"]
    cNumWet = int( cRow.at["Wet_Count"] )
    cGridId = ExGridNum( cMGridId )
    cModelId = ExModNum( cMGridId )
    for jJ in range(cNumWet):
        cPDep = float( cRow.at[BCCurCols[StartInd+jJ]] )
        MGridIDs[iCnt] = cMGridId
        GridIDs[iCnt] = cGridId
        ModelIDs[iCnt] = cModelId
        PDDepth[iCnt] = cPDep
        iCnt += 1
    # end of inner for
# end of outer for

In [284]:
GridIDs.min(), GridIDs.max()

(169, 210)

In [285]:
PDDepth.min(), PDDepth.max()

(0.20000057, 640.35443)

In [286]:
DataDict = { "MGrid_Id" : MGridIDs,
             "Grid_Id" : GridIDs,
             "Model_Id" : ModelIDs,
             "Precip_mm" : PDDepth, }
BCJulDayDF = pd.DataFrame( data=DataDict )

In [287]:
display( HTML( BCJulDayDF.describe().to_html() ))

Now want to save the Jul DataFrame as both a pickle and a feather so that can reuse it with both Python and R.

In [288]:
BCJulPCKF = os.path.normpath( os.path.join( OUT_DIR, "Jul_WetDep_CMIP5_BCCA_2011-2040.pickle" ) )
BCJulDayDF.to_pickle( BCJulPCKF )
BCJulFeatherF = os.path.normpath( os.path.join( OUT_DIR, "Jul_WetDep_CMIP5_BCCA_2011-2040.feather" ) )
BCJulDayDF.to_feather( BCJulFeatherF )

### Aug

Counts

In [289]:
LOAugDF = LOWetDF[LORootCols].loc[LOWetDF['Month'] == 8].copy()

In [290]:
display( HTML( LOAugDF.head().to_html() ) )

In [291]:
BCAugDF = BCWetDF[BCRootCols].loc[BCWetDF['Month'] == 8].copy()

In [292]:
display( HTML( BCAugDF.head().to_html() ) )

In [293]:
LOAugDF['Grid_Id'] = LOAugDF.apply( lambda row: ExGridNum(row['MGrid_Id']), axis=1 )
LOAugDF['Model_Id'] = LOAugDF.apply( lambda row: ExModNum(row['MGrid_Id']), axis=1 )
BCAugDF['Grid_Id'] = BCAugDF.apply( lambda row: ExGridNum(row['MGrid_Id']), axis=1 )
BCAugDF['Model_Id'] = BCAugDF.apply( lambda row: ExModNum(row['MGrid_Id']), axis=1 )

In [294]:
display( HTML( LOAugDF.head().to_html() ) )

In [295]:
display( HTML( BCAugDF.head().to_html() ) )

In [296]:
LOAugPCKF = os.path.normpath( os.path.join( OUT_DIR, "Aug_WetCnt_CMIP5_LOCA_2011-2040.pickle" ) )
LOAugDF.to_pickle( LOAugPCKF )
BCAugPCKF = os.path.normpath( os.path.join( OUT_DIR, "Aug_WetCnt_CMIP5_BCCA_2011-2040.pickle" ) )
BCAugDF.to_pickle( BCAugPCKF )

In [297]:
LOAugDF = LOAugDF.reset_index()
LOAugFeatherF = os.path.normpath( os.path.join( OUT_DIR, "Aug_WetCnt_CMIP5_LOCA_2011-2040.feather" ) )
LOAugDF.to_feather( LOAugFeatherF )
BCAugDF = BCAugDF.reset_index()
BCAugFeatherF = os.path.normpath( os.path.join( OUT_DIR, "Aug_WetCnt_CMIP5_BCCA_2011-2040.feather" ) )
BCAugDF.to_feather( BCAugFeatherF )

Depths

In [298]:
LOAugDF = LOWetDF[LOWetDF['Month'] == 8].copy()
BCAugDF = BCWetDF[BCWetDF['Month'] == 8].copy()

In [299]:
display( HTML( LOAugDF.head().to_html() ) )

In [300]:
LOAugMaxCnt = LOAugDF['Wet_Count'].max()
LOAugMaxCnt

33

In [301]:
BCAugMaxCnt = BCAugDF['Wet_Count'].max()
BCAugMaxCnt

48

In [302]:
LOCurCols = [LORootCols[0], LORootCols[4], LORootCols[5] ]
LOCurCols

['MGrid_Id', 'Month', 'Day']

In [303]:
BCCurCols = [BCRootCols[0], BCRootCols[4], BCRootCols[5] ]
BCCurCols

['MGrid_Id', 'Month', 'Day']

In [304]:
for jJ in range(LOAugMaxCnt):
    LOCurCols.append( LODayCols[jJ] )
# end for

In [305]:
for jJ in range(BCAugMaxCnt):
    BCCurCols.append( BCDayCols[jJ] )
# end for

In [306]:
LOAugDF = LOAugDF[LOCurCols].copy()
BCAugDF = BCAugDF[BCCurCols].copy()

In [307]:
LOAugDF.reset_index(drop=True, inplace=True)
BCAugDF.reset_index(drop=True, inplace=True)

In [308]:
display( HTML( LOAugDF.iloc[:10].to_html() ) )

In [309]:
display( HTML( BCAugDF.iloc[:10].to_html() ) )

In [310]:
LOAugTotDays = LOAugDF['Wet_Count'].sum()
LOAugTotDays

2698037

In [311]:
BCAugTotDays = BCAugDF['Wet_Count'].sum()
BCAugTotDays

2545621

Setup the arrays that will use to store all of the wet day precipitation depths

In [312]:
GridIDs = np.zeros( LOAugTotDays, dtype=np.int32 )
ModelIDs = np.zeros( LOAugTotDays, dtype=np.int32 )
PDDepth = np.zeros( LOAugTotDays, dtype=np.float32 )
MGridIDs = [ "%d" % x for x in GridIDs.tolist() ]

In [313]:
LONumAugWet = len( LOAugDF )
LONumAugWet

1047522

In [314]:
iCnt = 0
for iI in range(LONumAugWet):
    cRow = LOAugDF.loc[iI]
    cMGridId = cRow.at["MGrid_Id"]
    cNumWet = int( cRow.at["Wet_Count"] )
    cGridId = ExGridNum( cMGridId )
    cModelId = ExModNum( cMGridId )
    for jJ in range(cNumWet):
        cPDep = float( cRow.at[LOCurCols[StartInd+jJ]] )
        MGridIDs[iCnt] = cMGridId
        GridIDs[iCnt] = cGridId
        ModelIDs[iCnt] = cModelId
        PDDepth[iCnt] = cPDep
        iCnt += 1
    # end of inner for
# end of outer for

In [315]:
GridIDs.min(), GridIDs.max()

(1, 168)

In [316]:
PDDepth.min(), PDDepth.max()

(0.200002, 495.9523)

In [317]:
DataDict = { "MGrid_Id" : MGridIDs,
             "Grid_Id" : GridIDs,
             "Model_Id" : ModelIDs,
             "Precip_mm" : PDDepth, }
LOAugDayDF = pd.DataFrame( data=DataDict )

In [318]:
display( HTML( LOAugDayDF.describe().to_html() ))

Now want to save the Auguary DataFrame as both a pickle and a feather so that can reuse it with both Python and R.

In [319]:
LOAugPCKF = os.path.normpath( os.path.join( OUT_DIR, "Aug_WetDep_CMIP5_LOCA_2011-2040.pickle" ) )
LOAugDayDF.to_pickle( LOAugPCKF )
LOAugFeatherF = os.path.normpath( os.path.join( OUT_DIR, "Aug_WetDep_CMIP5_LOCA_2011-2040.feather" ) )
LOAugDayDF.to_feather( LOAugFeatherF )

Now BCCA, setup the arrays that will use to store all of the wet day precipitation depths

In [320]:
GridIDs = np.zeros( BCAugTotDays, dtype=np.int32 )
ModelIDs = np.zeros( BCAugTotDays, dtype=np.int32 )
PDDepth = np.zeros( BCAugTotDays, dtype=np.float32 )
MGridIDs = [ "%d" % x for x in GridIDs.tolist() ]

In [321]:
BCNumAugWet = len( BCAugDF )
BCNumAugWet

881638

In [322]:
iCnt = 0
for iI in range(BCNumAugWet):
    cRow = BCAugDF.loc[iI]
    cMGridId = cRow.at["MGrid_Id"]
    cNumWet = int( cRow.at["Wet_Count"] )
    cGridId = ExGridNum( cMGridId )
    cModelId = ExModNum( cMGridId )
    for jJ in range(cNumWet):
        cPDep = float( cRow.at[BCCurCols[StartInd+jJ]] )
        MGridIDs[iCnt] = cMGridId
        GridIDs[iCnt] = cGridId
        ModelIDs[iCnt] = cModelId
        PDDepth[iCnt] = cPDep
        iCnt += 1
    # end of inner for
# end of outer for

In [323]:
GridIDs.min(), GridIDs.max()

(169, 210)

In [324]:
PDDepth.min(), PDDepth.max()

(0.20000093, 721.7218)

In [325]:
DataDict = { "MGrid_Id" : MGridIDs,
             "Grid_Id" : GridIDs,
             "Model_Id" : ModelIDs,
             "Precip_mm" : PDDepth, }
BCAugDayDF = pd.DataFrame( data=DataDict )

In [326]:
display( HTML( BCAugDayDF.describe().to_html() ))

Now want to save the Aug DataFrame as both a pickle and a feather so that can reuse it with both Python and R.

In [327]:
BCAugPCKF = os.path.normpath( os.path.join( OUT_DIR, "Aug_WetDep_CMIP5_BCCA_2011-2040.pickle" ) )
BCAugDayDF.to_pickle( BCAugPCKF )
BCAugFeatherF = os.path.normpath( os.path.join( OUT_DIR, "Aug_WetDep_CMIP5_BCCA_2011-2040.feather" ) )
BCAugDayDF.to_feather( BCAugFeatherF )

### Sep

Counts

In [328]:
LOSepDF = LOWetDF[LORootCols].loc[LOWetDF['Month'] == 9].copy()

In [329]:
display( HTML( LOSepDF.head().to_html() ) )

In [330]:
BCSepDF = BCWetDF[BCRootCols].loc[BCWetDF['Month'] == 9].copy()

In [331]:
display( HTML( BCSepDF.head().to_html() ) )

In [332]:
LOSepDF['Grid_Id'] = LOSepDF.apply( lambda row: ExGridNum(row['MGrid_Id']), axis=1 )
LOSepDF['Model_Id'] = LOSepDF.apply( lambda row: ExModNum(row['MGrid_Id']), axis=1 )
BCSepDF['Grid_Id'] = BCSepDF.apply( lambda row: ExGridNum(row['MGrid_Id']), axis=1 )
BCSepDF['Model_Id'] = BCSepDF.apply( lambda row: ExModNum(row['MGrid_Id']), axis=1 )

In [333]:
display( HTML( LOSepDF.head().to_html() ) )

In [334]:
display( HTML( BCSepDF.head().to_html() ) )

In [335]:
LOSepPCKF = os.path.normpath( os.path.join( OUT_DIR, "Sep_WetCnt_CMIP5_LOCA_2011-2040.pickle" ) )
LOSepDF.to_pickle( LOSepPCKF )
BCSepPCKF = os.path.normpath( os.path.join( OUT_DIR, "Sep_WetCnt_CMIP5_BCCA_2011-2040.pickle" ) )
BCSepDF.to_pickle( BCSepPCKF )

In [336]:
LOSepDF = LOSepDF.reset_index()
LOSepFeatherF = os.path.normpath( os.path.join( OUT_DIR, "Sep_WetCnt_CMIP5_LOCA_2011-2040.feather" ) )
LOSepDF.to_feather( LOSepFeatherF )
BCSepDF = BCSepDF.reset_index()
BCSepFeatherF = os.path.normpath( os.path.join( OUT_DIR, "Sep_WetCnt_CMIP5_BCCA_2011-2040.feather" ) )
BCSepDF.to_feather( BCSepFeatherF )

Depths

In [337]:
LOSepDF = LOWetDF[LOWetDF['Month'] == 9].copy()
BCSepDF = BCWetDF[BCWetDF['Month'] == 9].copy()

In [338]:
display( HTML( LOSepDF.head().to_html() ) )

In [339]:
LOSepMaxCnt = LOSepDF['Wet_Count'].max()
LOSepMaxCnt

37

In [340]:
BCSepMaxCnt = BCSepDF['Wet_Count'].max()
BCSepMaxCnt

37

In [341]:
LOCurCols = [LORootCols[0], LORootCols[4], LORootCols[5] ]
LOCurCols

['MGrid_Id', 'Month', 'Day']

In [342]:
BCCurCols = [BCRootCols[0], BCRootCols[4], BCRootCols[5] ]
BCCurCols

['MGrid_Id', 'Month', 'Day']

In [343]:
for jJ in range(LOSepMaxCnt):
    LOCurCols.append( LODayCols[jJ] )
# end for

In [344]:
for jJ in range(BCSepMaxCnt):
    BCCurCols.append( BCDayCols[jJ] )
# end for

In [345]:
LOSepDF = LOSepDF[LOCurCols].copy()
BCSepDF = BCSepDF[BCCurCols].copy()

In [346]:
LOSepDF.reset_index(drop=True, inplace=True)
BCSepDF.reset_index(drop=True, inplace=True)

In [347]:
display( HTML( LOSepDF.iloc[:10].to_html() ) )

In [348]:
display( HTML( BCSepDF.iloc[:10].to_html() ) )

In [349]:
LOSepTotDays = LOSepDF['Wet_Count'].sum()
LOSepTotDays

3484121

In [350]:
BCSepTotDays = BCSepDF['Wet_Count'].sum()
BCSepTotDays

2463300

Setup the arrays that will use to store all of the wet day precipitation depths

In [351]:
GridIDs = np.zeros( LOSepTotDays, dtype=np.int32 )
ModelIDs = np.zeros( LOSepTotDays, dtype=np.int32 )
PDDepth = np.zeros( LOSepTotDays, dtype=np.float32 )
MGridIDs = [ "%d" % x for x in GridIDs.tolist() ]

In [352]:
LONumSepWet = len( LOSepDF )
LONumSepWet

1199904

In [353]:
iCnt = 0
for iI in range(LONumSepWet):
    cRow = LOSepDF.loc[iI]
    cMGridId = cRow.at["MGrid_Id"]
    cNumWet = int( cRow.at["Wet_Count"] )
    cGridId = ExGridNum( cMGridId )
    cModelId = ExModNum( cMGridId )
    for jJ in range(cNumWet):
        cPDep = float( cRow.at[LOCurCols[StartInd+jJ]] )
        MGridIDs[iCnt] = cMGridId
        GridIDs[iCnt] = cGridId
        ModelIDs[iCnt] = cModelId
        PDDepth[iCnt] = cPDep
        iCnt += 1
    # end of inner for
# end of outer for

In [354]:
GridIDs.min(), GridIDs.max()

(1, 168)

In [355]:
PDDepth.min(), PDDepth.max()

(0.20000143, 552.1317)

In [356]:
DataDict = { "MGrid_Id" : MGridIDs,
             "Grid_Id" : GridIDs,
             "Model_Id" : ModelIDs,
             "Precip_mm" : PDDepth, }
LOSepDayDF = pd.DataFrame( data=DataDict )

In [357]:
display( HTML( LOSepDayDF.describe().to_html() ))

Now want to save the Sepuary DataFrame as both a pickle and a feather so that can reuse it with both Python and R.

In [358]:
LOSepPCKF = os.path.normpath( os.path.join( OUT_DIR, "Sep_WetDep_CMIP5_LOCA_2011-2040.pickle" ) )
LOSepDayDF.to_pickle( LOSepPCKF )
LOSepFeatherF = os.path.normpath( os.path.join( OUT_DIR, "Sep_WetDep_CMIP5_LOCA_2011-2040.feather" ) )
LOSepDayDF.to_feather( LOSepFeatherF )

Now BCCA, setup the arrays that will use to store all of the wet day precipitation depths

In [359]:
GridIDs = np.zeros( BCSepTotDays, dtype=np.int32 )
ModelIDs = np.zeros( BCSepTotDays, dtype=np.int32 )
PDDepth = np.zeros( BCSepTotDays, dtype=np.float32 )
MGridIDs = [ "%d" % x for x in GridIDs.tolist() ]

In [360]:
BCNumSepWet = len( BCSepDF )
BCNumSepWet

807678

In [361]:
iCnt = 0
for iI in range(BCNumSepWet):
    cRow = BCSepDF.loc[iI]
    cMGridId = cRow.at["MGrid_Id"]
    cNumWet = int( cRow.at["Wet_Count"] )
    cGridId = ExGridNum( cMGridId )
    cModelId = ExModNum( cMGridId )
    for jJ in range(cNumWet):
        cPDep = float( cRow.at[BCCurCols[StartInd+jJ]] )
        MGridIDs[iCnt] = cMGridId
        GridIDs[iCnt] = cGridId
        ModelIDs[iCnt] = cModelId
        PDDepth[iCnt] = cPDep
        iCnt += 1
    # end of inner for
# end of outer for

In [362]:
GridIDs.min(), GridIDs.max()

(169, 210)

In [363]:
PDDepth.min(), PDDepth.max()

(0.20000245, 497.55463)

In [364]:
DataDict = { "MGrid_Id" : MGridIDs,
             "Grid_Id" : GridIDs,
             "Model_Id" : ModelIDs,
             "Precip_mm" : PDDepth, }
BCSepDayDF = pd.DataFrame( data=DataDict )

In [365]:
display( HTML( BCSepDayDF.describe().to_html() ))

Now want to save the Sep DataFrame as both a pickle and a feather so that can reuse it with both Python and R.

In [366]:
BCSepPCKF = os.path.normpath( os.path.join( OUT_DIR, "Sep_WetDep_CMIP5_BCCA_2011-2040.pickle" ) )
BCSepDayDF.to_pickle( BCSepPCKF )
BCSepFeatherF = os.path.normpath( os.path.join( OUT_DIR, "Sep_WetDep_CMIP5_BCCA_2011-2040.feather" ) )
BCSepDayDF.to_feather( BCSepFeatherF )

### Oct

Counts

In [367]:
LOOctDF = LOWetDF[LORootCols].loc[LOWetDF['Month'] == 10].copy()

In [368]:
display( HTML( LOOctDF.head().to_html() ) )

In [369]:
BCOctDF = BCWetDF[BCRootCols].loc[BCWetDF['Month'] == 10].copy()

In [370]:
display( HTML( BCOctDF.head().to_html() ) )

In [371]:
LOOctDF['Grid_Id'] = LOOctDF.apply( lambda row: ExGridNum(row['MGrid_Id']), axis=1 )
LOOctDF['Model_Id'] = LOOctDF.apply( lambda row: ExModNum(row['MGrid_Id']), axis=1 )
BCOctDF['Grid_Id'] = BCOctDF.apply( lambda row: ExGridNum(row['MGrid_Id']), axis=1 )
BCOctDF['Model_Id'] = BCOctDF.apply( lambda row: ExModNum(row['MGrid_Id']), axis=1 )

In [372]:
display( HTML( LOOctDF.head().to_html() ) )

In [373]:
display( HTML( BCOctDF.head().to_html() ) )

In [374]:
LOOctPCKF = os.path.normpath( os.path.join( OUT_DIR, "Oct_WetCnt_CMIP5_LOCA_2011-2040.pickle" ) )
LOOctDF.to_pickle( LOOctPCKF )
BCOctPCKF = os.path.normpath( os.path.join( OUT_DIR, "Oct_WetCnt_CMIP5_BCCA_2011-2040.pickle" ) )
BCOctDF.to_pickle( BCOctPCKF )

In [375]:
LOOctDF = LOOctDF.reset_index()
LOOctFeatherF = os.path.normpath( os.path.join( OUT_DIR, "Oct_WetCnt_CMIP5_LOCA_2011-2040.feather" ) )
LOOctDF.to_feather( LOOctFeatherF )
BCOctDF = BCOctDF.reset_index()
BCOctFeatherF = os.path.normpath( os.path.join( OUT_DIR, "Oct_WetCnt_CMIP5_BCCA_2011-2040.feather" ) )
BCOctDF.to_feather( BCOctFeatherF )

Depths

In [376]:
LOOctDF = LOWetDF[LOWetDF['Month'] == 10].copy()
BCOctDF = BCWetDF[BCWetDF['Month'] == 10].copy()

In [377]:
display( HTML( LOOctDF.head().to_html() ) )

In [378]:
LOOctMaxCnt = LOOctDF['Wet_Count'].max()
LOOctMaxCnt

23

In [379]:
BCOctMaxCnt = BCOctDF['Wet_Count'].max()
BCOctMaxCnt

26

In [380]:
LOCurCols = [LORootCols[0], LORootCols[4], LORootCols[5] ]
LOCurCols

['MGrid_Id', 'Month', 'Day']

In [381]:
BCCurCols = [BCRootCols[0], BCRootCols[4], BCRootCols[5] ]
BCCurCols

['MGrid_Id', 'Month', 'Day']

In [382]:
for jJ in range(LOOctMaxCnt):
    LOCurCols.append( LODayCols[jJ] )
# end for

In [383]:
for jJ in range(BCOctMaxCnt):
    BCCurCols.append( BCDayCols[jJ] )
# end for

In [384]:
LOOctDF = LOOctDF[LOCurCols].copy()
BCOctDF = BCOctDF[BCCurCols].copy()

In [385]:
LOOctDF.reset_index(drop=True, inplace=True)
BCOctDF.reset_index(drop=True, inplace=True)

In [386]:
display( HTML( LOOctDF.iloc[:10].to_html() ) )

In [387]:
display( HTML( BCOctDF.iloc[:10].to_html() ) )

In [388]:
LOOctTotDays = LOOctDF['Wet_Count'].sum()
LOOctTotDays

2754651

In [389]:
BCOctTotDays = BCOctDF['Wet_Count'].sum()
BCOctTotDays

1745980

Setup the arrays that will use to store all of the wet day precipitation depths

In [390]:
GridIDs = np.zeros( LOOctTotDays, dtype=np.int32 )
ModelIDs = np.zeros( LOOctTotDays, dtype=np.int32 )
PDDepth = np.zeros( LOOctTotDays, dtype=np.float32 )
MGridIDs = [ "%d" % x for x in GridIDs.tolist() ]

In [391]:
LONumOctWet = len( LOOctDF )
LONumOctWet

1108727

In [392]:
iCnt = 0
for iI in range(LONumOctWet):
    cRow = LOOctDF.loc[iI]
    cMGridId = cRow.at["MGrid_Id"]
    cNumWet = int( cRow.at["Wet_Count"] )
    cGridId = ExGridNum( cMGridId )
    cModelId = ExModNum( cMGridId )
    for jJ in range(cNumWet):
        cPDep = float( cRow.at[LOCurCols[StartInd+jJ]] )
        MGridIDs[iCnt] = cMGridId
        GridIDs[iCnt] = cGridId
        ModelIDs[iCnt] = cModelId
        PDDepth[iCnt] = cPDep
        iCnt += 1
    # end of inner for
# end of outer for

In [393]:
GridIDs.min(), GridIDs.max()

(1, 168)

In [394]:
PDDepth.min(), PDDepth.max()

(0.20000184, 591.96387)

In [395]:
DataDict = { "MGrid_Id" : MGridIDs,
             "Grid_Id" : GridIDs,
             "Model_Id" : ModelIDs,
             "Precip_mm" : PDDepth, }
LOOctDayDF = pd.DataFrame( data=DataDict )

In [396]:
display( HTML( LOOctDayDF.describe().to_html() ))

Now want to save the Octuary DataFrame as both a pickle and a feather so that can reuse it with both Python and R.

In [397]:
LOOctPCKF = os.path.normpath( os.path.join( OUT_DIR, "Oct_WetDep_CMIP5_LOCA_2011-2040.pickle" ) )
LOOctDayDF.to_pickle( LOOctPCKF )
LOOctFeatherF = os.path.normpath( os.path.join( OUT_DIR, "Oct_WetDep_CMIP5_LOCA_2011-2040.feather" ) )
LOOctDayDF.to_feather( LOOctFeatherF )

Now BCCA, setup the arrays that will use to store all of the wet day precipitation depths

In [398]:
GridIDs = np.zeros( BCOctTotDays, dtype=np.int32 )
ModelIDs = np.zeros( BCOctTotDays, dtype=np.int32 )
PDDepth = np.zeros( BCOctTotDays, dtype=np.float32 )
MGridIDs = [ "%d" % x for x in GridIDs.tolist() ]

In [399]:
BCNumOctWet = len( BCOctDF )
BCNumOctWet

712300

In [400]:
iCnt = 0
for iI in range(BCNumOctWet):
    cRow = BCOctDF.loc[iI]
    cMGridId = cRow.at["MGrid_Id"]
    cNumWet = int( cRow.at["Wet_Count"] )
    cGridId = ExGridNum( cMGridId )
    cModelId = ExModNum( cMGridId )
    for jJ in range(cNumWet):
        cPDep = float( cRow.at[BCCurCols[StartInd+jJ]] )
        MGridIDs[iCnt] = cMGridId
        GridIDs[iCnt] = cGridId
        ModelIDs[iCnt] = cModelId
        PDDepth[iCnt] = cPDep
        iCnt += 1
    # end of inner for
# end of outer for

In [401]:
GridIDs.min(), GridIDs.max()

(169, 210)

In [402]:
PDDepth.min(), PDDepth.max()

(0.20000152, 318.5694)

In [403]:
DataDict = { "MGrid_Id" : MGridIDs,
             "Grid_Id" : GridIDs,
             "Model_Id" : ModelIDs,
             "Precip_mm" : PDDepth, }
BCOctDayDF = pd.DataFrame( data=DataDict )

In [404]:
display( HTML( BCOctDayDF.describe().to_html() ))

Now want to save the Oct DataFrame as both a pickle and a feather so that can reuse it with both Python and R.

In [405]:
BCOctPCKF = os.path.normpath( os.path.join( OUT_DIR, "Oct_WetDep_CMIP5_BCCA_2011-2040.pickle" ) )
BCOctDayDF.to_pickle( BCOctPCKF )
BCOctFeatherF = os.path.normpath( os.path.join( OUT_DIR, "Oct_WetDep_CMIP5_BCCA_2011-2040.feather" ) )
BCOctDayDF.to_feather( BCOctFeatherF )

### Nov

Counts

In [406]:
LONovDF = LOWetDF[LORootCols].loc[LOWetDF['Month'] == 11].copy()

In [407]:
display( HTML( LONovDF.head().to_html() ) )

In [408]:
BCNovDF = BCWetDF[BCRootCols].loc[BCWetDF['Month'] == 11].copy()

In [409]:
display( HTML( BCNovDF.head().to_html() ) )

In [410]:
LONovDF['Grid_Id'] = LONovDF.apply( lambda row: ExGridNum(row['MGrid_Id']), axis=1 )
LONovDF['Model_Id'] = LONovDF.apply( lambda row: ExModNum(row['MGrid_Id']), axis=1 )
BCNovDF['Grid_Id'] = BCNovDF.apply( lambda row: ExGridNum(row['MGrid_Id']), axis=1 )
BCNovDF['Model_Id'] = BCNovDF.apply( lambda row: ExModNum(row['MGrid_Id']), axis=1 )

In [411]:
display( HTML( LONovDF.head().to_html() ) )

In [412]:
display( HTML( BCNovDF.head().to_html() ) )

In [413]:
LONovPCKF = os.path.normpath( os.path.join( OUT_DIR, "Nov_WetCnt_CMIP5_LOCA_2011-2040.pickle" ) )
LONovDF.to_pickle( LONovPCKF )
BCNovPCKF = os.path.normpath( os.path.join( OUT_DIR, "Nov_WetCnt_CMIP5_BCCA_2011-2040.pickle" ) )
BCNovDF.to_pickle( BCNovPCKF )

In [414]:
LONovDF = LONovDF.reset_index()
LONovFeatherF = os.path.normpath( os.path.join( OUT_DIR, "Nov_WetCnt_CMIP5_LOCA_2011-2040.feather" ) )
LONovDF.to_feather( LONovFeatherF )
BCNovDF = BCNovDF.reset_index()
BCNovFeatherF = os.path.normpath( os.path.join( OUT_DIR, "Nov_WetCnt_CMIP5_BCCA_2011-2040.feather" ) )
BCNovDF.to_feather( BCNovFeatherF )

Depths

In [415]:
LONovDF = LOWetDF[LOWetDF['Month'] == 11].copy()
BCNovDF = BCWetDF[BCWetDF['Month'] == 11].copy()

In [416]:
display( HTML( LONovDF.head().to_html() ) )

In [417]:
LONovMaxCnt = LONovDF['Wet_Count'].max()
LONovMaxCnt

16

In [418]:
BCNovMaxCnt = BCNovDF['Wet_Count'].max()
BCNovMaxCnt

18

In [419]:
LOCurCols = [LORootCols[0], LORootCols[4], LORootCols[5] ]
LOCurCols

['MGrid_Id', 'Month', 'Day']

In [420]:
BCCurCols = [BCRootCols[0], BCRootCols[4], BCRootCols[5] ]
BCCurCols

['MGrid_Id', 'Month', 'Day']

In [421]:
for jJ in range(LONovMaxCnt):
    LOCurCols.append( LODayCols[jJ] )
# end for

In [422]:
for jJ in range(BCNovMaxCnt):
    BCCurCols.append( BCDayCols[jJ] )
# end for

In [423]:
LONovDF = LONovDF[LOCurCols].copy()
BCNovDF = BCNovDF[BCCurCols].copy()

In [424]:
LONovDF.reset_index(drop=True, inplace=True)
BCNovDF.reset_index(drop=True, inplace=True)

In [425]:
display( HTML( LONovDF.iloc[:10].to_html() ) )

In [426]:
display( HTML( BCNovDF.iloc[:10].to_html() ) )

In [427]:
LONovTotDays = LONovDF['Wet_Count'].sum()
LONovTotDays

2308082

In [428]:
BCNovTotDays = BCNovDF['Wet_Count'].sum()
BCNovTotDays

1352741

Setup the arrays that will use to store all of the wet day precipitation depths

In [429]:
GridIDs = np.zeros( LONovTotDays, dtype=np.int32 )
ModelIDs = np.zeros( LONovTotDays, dtype=np.int32 )
PDDepth = np.zeros( LONovTotDays, dtype=np.float32 )
MGridIDs = [ "%d" % x for x in GridIDs.tolist() ]

In [430]:
LONumNovWet = len( LONovDF )
LONumNovWet

1089595

In [431]:
iCnt = 0
for iI in range(LONumNovWet):
    cRow = LONovDF.loc[iI]
    cMGridId = cRow.at["MGrid_Id"]
    cNumWet = int( cRow.at["Wet_Count"] )
    cGridId = ExGridNum( cMGridId )
    cModelId = ExModNum( cMGridId )
    for jJ in range(cNumWet):
        cPDep = float( cRow.at[LOCurCols[StartInd+jJ]] )
        MGridIDs[iCnt] = cMGridId
        GridIDs[iCnt] = cGridId
        ModelIDs[iCnt] = cModelId
        PDDepth[iCnt] = cPDep
        iCnt += 1
    # end of inner for
# end of outer for

In [432]:
GridIDs.min(), GridIDs.max()

(1, 168)

In [433]:
PDDepth.min(), PDDepth.max()

(0.20000046, 202.97487)

In [434]:
DataDict = { "MGrid_Id" : MGridIDs,
             "Grid_Id" : GridIDs,
             "Model_Id" : ModelIDs,
             "Precip_mm" : PDDepth, }
LONovDayDF = pd.DataFrame( data=DataDict )

In [435]:
display( HTML( LONovDayDF.describe().to_html() ))

Now want to save the Novuary DataFrame as both a pickle and a feather so that can reuse it with both Python and R.

In [436]:
LONovPCKF = os.path.normpath( os.path.join( OUT_DIR, "Nov_WetDep_CMIP5_LOCA_2011-2040.pickle" ) )
LONovDayDF.to_pickle( LONovPCKF )
LONovFeatherF = os.path.normpath( os.path.join( OUT_DIR, "Nov_WetDep_CMIP5_LOCA_2011-2040.feather" ) )
LONovDayDF.to_feather( LONovFeatherF )

Now BCCA, setup the arrays that will use to store all of the wet day precipitation depths

In [437]:
GridIDs = np.zeros( BCNovTotDays, dtype=np.int32 )
ModelIDs = np.zeros( BCNovTotDays, dtype=np.int32 )
PDDepth = np.zeros( BCNovTotDays, dtype=np.float32 )
MGridIDs = [ "%d" % x for x in GridIDs.tolist() ]

In [438]:
BCNumNovWet = len( BCNovDF )
BCNumNovWet

661202

In [439]:
iCnt = 0
for iI in range(BCNumNovWet):
    cRow = BCNovDF.loc[iI]
    cMGridId = cRow.at["MGrid_Id"]
    cNumWet = int( cRow.at["Wet_Count"] )
    cGridId = ExGridNum( cMGridId )
    cModelId = ExModNum( cMGridId )
    for jJ in range(cNumWet):
        cPDep = float( cRow.at[BCCurCols[StartInd+jJ]] )
        MGridIDs[iCnt] = cMGridId
        GridIDs[iCnt] = cGridId
        ModelIDs[iCnt] = cModelId
        PDDepth[iCnt] = cPDep
        iCnt += 1
    # end of inner for
# end of outer for

In [440]:
GridIDs.min(), GridIDs.max()

(169, 210)

In [441]:
PDDepth.min(), PDDepth.max()

(0.20000371, 190.50197)

In [442]:
DataDict = { "MGrid_Id" : MGridIDs,
             "Grid_Id" : GridIDs,
             "Model_Id" : ModelIDs,
             "Precip_mm" : PDDepth, }
BCNovDayDF = pd.DataFrame( data=DataDict )

In [443]:
display( HTML( BCNovDayDF.describe().to_html() ))

Now want to save the Nov DataFrame as both a pickle and a feather so that can reuse it with both Python and R.

In [444]:
BCNovPCKF = os.path.normpath( os.path.join( OUT_DIR, "Nov_WetDep_CMIP5_BCCA_2011-2040.pickle" ) )
BCNovDayDF.to_pickle( BCNovPCKF )
BCNovFeatherF = os.path.normpath( os.path.join( OUT_DIR, "Nov_WetDep_CMIP5_BCCA_2011-2040.feather" ) )
BCNovDayDF.to_feather( BCNovFeatherF )

### Dec

Counts

In [445]:
LODecDF = LOWetDF[LORootCols].loc[LOWetDF['Month'] == 12].copy()

In [446]:
display( HTML( LODecDF.head().to_html() ) )

In [447]:
BCDecDF = BCWetDF[BCRootCols].loc[BCWetDF['Month'] == 12].copy()

In [448]:
display( HTML( BCDecDF.head().to_html() ) )

In [449]:
LODecDF['Grid_Id'] = LODecDF.apply( lambda row: ExGridNum(row['MGrid_Id']), axis=1 )
LODecDF['Model_Id'] = LODecDF.apply( lambda row: ExModNum(row['MGrid_Id']), axis=1 )
BCDecDF['Grid_Id'] = BCDecDF.apply( lambda row: ExGridNum(row['MGrid_Id']), axis=1 )
BCDecDF['Model_Id'] = BCDecDF.apply( lambda row: ExModNum(row['MGrid_Id']), axis=1 )

In [450]:
display( HTML( LODecDF.head().to_html() ) )

In [451]:
display( HTML( BCDecDF.head().to_html() ) )

In [452]:
LODecPCKF = os.path.normpath( os.path.join( OUT_DIR, "Dec_WetCnt_CMIP5_LOCA_2011-2040.pickle" ) )
LODecDF.to_pickle( LODecPCKF )
BCDecPCKF = os.path.normpath( os.path.join( OUT_DIR, "Dec_WetCnt_CMIP5_BCCA_2011-2040.pickle" ) )
BCDecDF.to_pickle( BCDecPCKF )

In [453]:
LODecDF = LODecDF.reset_index()
LODecFeatherF = os.path.normpath( os.path.join( OUT_DIR, "Dec_WetCnt_CMIP5_LOCA_2011-2040.feather" ) )
LODecDF.to_feather( LODecFeatherF )
BCDecDF = BCDecDF.reset_index()
BCDecFeatherF = os.path.normpath( os.path.join( OUT_DIR, "Dec_WetCnt_CMIP5_BCCA_2011-2040.feather" ) )
BCDecDF.to_feather( BCDecFeatherF )

Depths

In [454]:
LODecDF = LOWetDF[LOWetDF['Month'] == 12].copy()
BCDecDF = BCWetDF[BCWetDF['Month'] == 12].copy()

In [455]:
display( HTML( LODecDF.head().to_html() ) )

In [456]:
LODecMaxCnt = LODecDF['Wet_Count'].max()
LODecMaxCnt

16

In [457]:
BCDecMaxCnt = BCDecDF['Wet_Count'].max()
BCDecMaxCnt

20

In [458]:
LOCurCols = [LORootCols[0], LORootCols[4], LORootCols[5] ]
LOCurCols

['MGrid_Id', 'Month', 'Day']

In [459]:
BCCurCols = [BCRootCols[0], BCRootCols[4], BCRootCols[5] ]
BCCurCols

['MGrid_Id', 'Month', 'Day']

In [460]:
for jJ in range(LODecMaxCnt):
    LOCurCols.append( LODayCols[jJ] )
# end for

In [461]:
for jJ in range(BCDecMaxCnt):
    BCCurCols.append( BCDayCols[jJ] )
# end for

In [462]:
LODecDF = LODecDF[LOCurCols].copy()
BCDecDF = BCDecDF[BCCurCols].copy()

In [463]:
LODecDF.reset_index(drop=True, inplace=True)
BCDecDF.reset_index(drop=True, inplace=True)

In [464]:
display( HTML( LODecDF.iloc[:10].to_html() ) )

In [465]:
display( HTML( BCDecDF.iloc[:10].to_html() ) )

In [466]:
LODecTotDays = LODecDF['Wet_Count'].sum()
LODecTotDays

1896575

In [467]:
BCDecTotDays = BCDecDF['Wet_Count'].sum()
BCDecTotDays

1285279

Setup the arrays that will use to store all of the wet day precipitation depths

In [468]:
GridIDs = np.zeros( LODecTotDays, dtype=np.int32 )
ModelIDs = np.zeros( LODecTotDays, dtype=np.int32 )
PDDepth = np.zeros( LODecTotDays, dtype=np.float32 )
MGridIDs = [ "%d" % x for x in GridIDs.tolist() ]

In [469]:
LONumDecWet = len( LODecDF )
LONumDecWet

1018618

In [470]:
iCnt = 0
for iI in range(LONumDecWet):
    cRow = LODecDF.loc[iI]
    cMGridId = cRow.at["MGrid_Id"]
    cNumWet = int( cRow.at["Wet_Count"] )
    cGridId = ExGridNum( cMGridId )
    cModelId = ExModNum( cMGridId )
    for jJ in range(cNumWet):
        cPDep = float( cRow.at[LOCurCols[StartInd+jJ]] )
        MGridIDs[iCnt] = cMGridId
        GridIDs[iCnt] = cGridId
        ModelIDs[iCnt] = cModelId
        PDDepth[iCnt] = cPDep
        iCnt += 1
    # end of inner for
# end of outer for

In [471]:
GridIDs.min(), GridIDs.max()

(1, 168)

In [472]:
PDDepth.min(), PDDepth.max()

(0.2000001, 266.7767)

In [473]:
DataDict = { "MGrid_Id" : MGridIDs,
             "Grid_Id" : GridIDs,
             "Model_Id" : ModelIDs,
             "Precip_mm" : PDDepth, }
LODecDayDF = pd.DataFrame( data=DataDict )

In [474]:
display( HTML( LODecDayDF.describe().to_html() ))

Now want to save the Dec DataFrame as both a pickle and a feather so that can reuse it with both Python and R.

In [475]:
LODecPCKF = os.path.normpath( os.path.join( OUT_DIR, "Dec_WetDep_CMIP5_LOCA_2011-2040.pickle" ) )
LODecDayDF.to_pickle( LODecPCKF )
LODecFeatherF = os.path.normpath( os.path.join( OUT_DIR, "Dec_WetDep_CMIP5_LOCA_2011-2040.feather" ) )
LODecDayDF.to_feather( LODecFeatherF )

Now BCCA, setup the arrays that will use to store all of the wet day precipitation depths

In [476]:
GridIDs = np.zeros( BCDecTotDays, dtype=np.int32 )
ModelIDs = np.zeros( BCDecTotDays, dtype=np.int32 )
PDDepth = np.zeros( BCDecTotDays, dtype=np.float32 )
MGridIDs = [ "%d" % x for x in GridIDs.tolist() ]

In [477]:
BCNumDecWet = len( BCDecDF )
BCNumDecWet

662197

In [478]:
iCnt = 0
for iI in range(BCNumDecWet):
    cRow = BCDecDF.loc[iI]
    cMGridId = cRow.at["MGrid_Id"]
    cNumWet = int( cRow.at["Wet_Count"] )
    cGridId = ExGridNum( cMGridId )
    cModelId = ExModNum( cMGridId )
    for jJ in range(cNumWet):
        cPDep = float( cRow.at[BCCurCols[StartInd+jJ]] )
        MGridIDs[iCnt] = cMGridId
        GridIDs[iCnt] = cGridId
        ModelIDs[iCnt] = cModelId
        PDDepth[iCnt] = cPDep
        iCnt += 1
    # end of inner for
# end of outer for

In [479]:
GridIDs.min(), GridIDs.max()

(169, 210)

In [480]:
PDDepth.min(), PDDepth.max()

(0.20000163, 145.15567)

In [481]:
DataDict = { "MGrid_Id" : MGridIDs,
             "Grid_Id" : GridIDs,
             "Model_Id" : ModelIDs,
             "Precip_mm" : PDDepth, }
BCDecDayDF = pd.DataFrame( data=DataDict )

In [482]:
display( HTML( BCDecDayDF.describe().to_html() ))

Now want to save the Decuary DataFrame as both a pickle and a feather so that can reuse it with both Python and R.

In [483]:
BCDecPCKF = os.path.normpath( os.path.join( OUT_DIR, "Dec_WetDep_CMIP5_BCCA_2011-2040.pickle" ) )
BCDecDayDF.to_pickle( BCDecPCKF )
BCDecFeatherF = os.path.normpath( os.path.join( OUT_DIR, "Dec_WetDep_CMIP5_BCCA_2011-2040.feather" ) )
BCDecDayDF.to_feather( BCDecFeatherF )